Repository UQcsse3200/2024-studio-2, pull requests merged in 2024-09, with the labels that each got.

#236 3 inventory items sprint 2
  .gitignore
  hs_err_pid22624.log
  hs_err_pid23180.log
  hs_err_pid27832.log
  saves/quests.json
  source/core/assets/Inventory/hotbar.png
  source/core/assets/Inventory/inventory.atlas
  source/core/assets/Inventory/inventory.json
  source/core/assets/Inventory/inventory.png
  source/core/assets/Inventory/pixel_32.fnt
  source/core/assets/Inventory/pixel_32.png
  source/core/assets/Inventory/skinforslot.atlas
  source/core/assets/Inventory/skinforslot.json
  source/core/assets/Inventory/skinforslot.png
  source/core/assets/configs/ForestGameAreaConfig.json
  source/core/assets/configs/ForestGameAreaConfigs/entitySpawn.json
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainComponent.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainLoader.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainLoaderComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerInventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/player/PlayerInventoryHotbarDisplay.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/physics/components/PhysicsComponent.java
Labels: Sprint 2, Team 3, Team 8, Collaboration Ticket

#234 4/Fixing Lag and Integrating DialogueBoxService with Items
  source/core/assets/images/enemy-chicken.atlas
  source/core/assets/images/enemy-chicken.png
  source/core/assets/images/enemy-frog.atlas
  source/core/assets/images/enemy-frog.png
  source/core/assets/images/enemy-monkey.atlas
  source/core/assets/images/enemy-monkey.png
  source/core/assets/images/frog.png
  source/core/assets/images/monkey.png
  source/core/src/main/com/csse3200/game/components/tasks/ChaseTask.java
  source/core/src/main/com/csse3200/game/components/tasks/ItemProximityTask.java
  source/core/src/main/com/csse3200/game/components/tasks/PauseTask.java
  source/core/src/main/com/csse3200/game/entities/DialogueBoxService.java
  source/core/src/main/com/csse3200/game/entities/configs/BaseEnemyEntityConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/BaseEntityConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/BaseFriendlyEntityConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/EnemyFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/services/ServiceLocator.java
  source/core/src/main/com/csse3200/game/ui/DialogueBox.java
  source/core/src/test/com/csse3200/game/areas/ForestGameAreaTest.java
  source/core/src/test/com/csse3200/game/components/ComponentTest.java
  source/core/src/test/com/csse3200/game/components/tasks/ItemProximityTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/PauseTaskTest.java
  source/core/src/test/com/csse3200/game/entities/DialogueBoxServiceTest.java
  source/core/src/test/com/csse3200/game/entities/EntityTest.java
  source/core/src/test/com/csse3200/game/entities/factories/EnemyFactoryTest.java
Labels: Sprint 2, Team 3, Team 4, Collaboration Ticket

#240 Proposed Update to Combat Logic Framework
  source/core/src/main/com/csse3200/game/components/combat/CombatManager.java
  source/core/src/main/com/csse3200/game/components/combat/move/CombatMoveComponent.java
Labels: enhancement, Sprint 2, Team 9, Team 10, Collaboration Ticket

#239 3 inventory items sprint 2
  source/core/assets/configs/ForestGameAreaConfig.json
  source/core/assets/configs/ForestGameAreaConfigs/entitySpawn.json
  source/core/assets/configs/ForestGameAreaConfigs/textures.json
  source/core/assets/images/foodtextures/download.png
  source/core/assets/images/potiontexture/defense.png
  source/core/assets/images/potiontexture/speed.png
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/ForestGameAreaConfigs/EntitySpawnConfig.java
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerInventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/player/PlayerInventoryHotbarDisplay.java
  source/core/src/main/com/csse3200/game/components/tasks/TimedUseItemTask.java
  source/core/src/main/com/csse3200/game/entities/configs/BaseEntityConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/ItemFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/inventory/items/ItemUsageContext.java
  source/core/src/main/com/csse3200/game/inventory/items/TimedUseItem.java
  source/core/src/main/com/csse3200/game/inventory/items/effects/AbstractEffect.java
  source/core/src/main/com/csse3200/game/inventory/items/effects/feeding/FeedEffect.java
  source/core/src/main/com/csse3200/game/inventory/items/effects/healing/HealEffect.java
  source/core/src/main/com/csse3200/game/inventory/items/food/AbstractFood.java
  source/core/src/main/com/csse3200/game/inventory/items/food/Foods.java
  source/core/src/main/com/csse3200/game/inventory/items/potions/AbstractPotion.java
  source/core/src/main/com/csse3200/game/inventory/items/potions/AttackPotion.java
  source/core/src/main/com/csse3200/game/inventory/items/potions/DefensePotion.java
  source/core/src/main/com/csse3200/game/inventory/items/potions/HealingPotion.java
  source/core/src/main/com/csse3200/game/inventory/items/potions/SpeedPotion.java
  source/core/src/test/com/csse3200/game/components/CombatStatsComponentTest.java
  source/core/src/test/com/csse3200/game/components/tasks/ItemProximityTaskTest.java
  source/core/src/test/com/csse3200/game/entities/factories/ItemFactoryTest.java
  source/core/src/test/com/csse3200/game/inventory/items/AbstractFoodTest.java
  source/core/src/test/com/csse3200/game/inventory/items/TimedUseItemTest.java
  source/core/src/test/com/csse3200/game/inventory/items/effects/AbstractEffectTest.java
  source/core/src/test/com/csse3200/game/inventory/items/potions/AbstractPotionTest.java
Labels: Sprint 2, Team 3

#251 CombatMove Refactoring and Combat End
  source/core/src/main/com/csse3200/game/components/combat/CombatActions.java
  source/core/src/main/com/csse3200/game/components/combat/CombatExitDisplay.java
  source/core/src/main/com/csse3200/game/components/combat/CombatManager.java
  source/core/src/main/com/csse3200/game/components/combat/move/AttackMove.java
  source/core/src/main/com/csse3200/game/components/combat/move/CombatMove.java
  source/core/src/main/com/csse3200/game/components/combat/move/CombatMoveComponent.java
  source/core/src/main/com/csse3200/game/components/combat/move/GuardMove.java
  source/core/src/main/com/csse3200/game/components/combat/move/SleepMove.java
  source/core/src/main/com/csse3200/game/components/combat/move/SpecialMove.java
  source/core/src/main/com/csse3200/game/screens/CombatScreen.java
Labels: enhancement, Sprint 2, Team 9, Team 10, Collaboration Ticket

#254 4/ Adding Fish FNPC & Refactoring
  source/core/assets/configs/ForestGameAreaConfig.json
  source/core/assets/configs/ForestGameAreaConfigs/entitySpawn.json
  source/core/assets/configs/ForestGameAreaConfigs/sounds.json
  source/core/assets/configs/ForestGameAreaConfigs/textures.json
  source/core/assets/configs/NPCs.json
  source/core/assets/images/Fish.atlas
  source/core/assets/images/Fish.png
  source/core/assets/sounds/FishBubble.wav
  source/core/assets/sounds/eagle-scream.mp3
  source/core/assets/sounds/eagle-scream.wav
  source/core/assets/sounds/mooing-cow.mp3
  source/core/assets/sounds/mooing-cow.wav
  source/core/assets/sounds/snake-hiss.mp3
  source/core/assets/sounds/snake-hiss.wav
  source/core/assets/sounds/tiger-roar.mp3
  source/core/assets/sounds/tiger-roar.wav
  source/core/assets/sounds/turtle-hiss.mp3
  source/core/assets/sounds/turtle-hiss.wav
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/ForestGameAreaConfigs/EntitySpawnConfig.java
  source/core/src/main/com/csse3200/game/components/player/PlayerInventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/tasks/ItemProximityTask.java
  source/core/src/main/com/csse3200/game/entities/configs/NPCConfigs.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/services/ServiceLocator.java
  source/core/src/test/com/csse3200/game/components/tasks/ItemProximityTaskTest.java
  source/core/src/test/com/csse3200/game/entities/DialogueBoxServiceTest.java
  source/core/src/test/com/csse3200/game/entities/factories/NPCFactoryTest.java
Labels: Team 4

#255 Fixed terrain not loading after first game.
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainComponent.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainLoader.java
Labels: bug, enhancement, Sprint 2

#256 4: Magpie NPC
  source/core/assets/configs/ForestGameAreaConfigs/entitySpawn.json
  source/core/assets/configs/ForestGameAreaConfigs/sounds.json
  source/core/assets/configs/ForestGameAreaConfigs/textures.json
  source/core/assets/configs/NPCs.json
  source/core/assets/images/magpie.atlas
  source/core/assets/images/magpie.png
  source/core/assets/sounds/aus-magpie.wav
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/ForestGameAreaConfigs/EntitySpawnConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/NPCConfigs.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/test/com/csse3200/game/entities/factories/NPCFactoryTest.java
Labels: Team 4

#265 Merging LootBox functionality into main.
  source/core/assets/images/chests/fancy-chest.png
  source/core/assets/images/chests/fancy-smancy-chest.png
  source/core/assets/images/chests/ordinary-chest.png
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/lootboxview/LootBoxOverlayComponent.java
  source/core/src/main/com/csse3200/game/components/minigames/MiniGamesScores.java
  source/core/src/main/com/csse3200/game/components/player/PlayerInventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/tasks/ItemProximityTask.java
  source/core/src/main/com/csse3200/game/entities/factories/ItemFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/inventory/items/lootbox/LootBox.java
  source/core/src/main/com/csse3200/game/inventory/items/lootbox/configs/BaseLootTable.java
  source/core/src/main/com/csse3200/game/inventory/items/lootbox/configs/EarlyGameLootTable.java
  source/core/src/main/com/csse3200/game/inventory/items/lootbox/configs/LateGameLootTable.java
  source/core/src/main/com/csse3200/game/inventory/items/lootbox/configs/LootItemConfig.java
  source/core/src/main/com/csse3200/game/inventory/items/lootbox/configs/MediumGameLootTable.java
  source/core/src/main/com/csse3200/game/inventory/items/lootbox/rarities/EarlyGameLootBox.java
  source/core/src/main/com/csse3200/game/inventory/items/lootbox/rarities/LateGameLootBox.java
  source/core/src/main/com/csse3200/game/inventory/items/lootbox/rarities/MediumGameLootBox.java
  source/core/src/main/com/csse3200/game/screens/EndMiniGameScreen.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/services/ServiceContainer.java
  source/core/src/test/com/csse3200/game/components/lootbox/LootBoxTest.java
  source/core/src/test/com/csse3200/game/components/minigames/MiniGameScoresTest.java
Labels: Task Ticket, Team 3

#269 Added calculations for enemy multi-hits attacks. Added a numHitsLanded parameter in combat move executions.
  source/core/src/main/com/csse3200/game/components/combat/CombatManager.java
  source/core/src/main/com/csse3200/game/components/combat/move/AttackMove.java
  source/core/src/main/com/csse3200/game/components/combat/move/CombatMove.java
  source/core/src/main/com/csse3200/game/components/combat/move/CombatMoveComponent.java
  source/core/src/main/com/csse3200/game/components/combat/move/GuardMove.java
  source/core/src/main/com/csse3200/game/components/combat/move/SleepMove.java
  source/core/src/main/com/csse3200/game/components/combat/move/SpecialMove.java
Labels: Team 10

#274 Implementation of new mini-game Birdie Dash
  source/core/assets/images/minigames/bird.png
  source/core/assets/images/minigames/coin.png
  source/core/assets/images/minigames/pipe.png
  source/core/assets/images/minigames/spikes.png
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/components/minigames/MinigameRenderer.java
  source/core/src/main/com/csse3200/game/components/minigames/birdieDash/BirdieDashGame.java
  source/core/src/main/com/csse3200/game/components/minigames/birdieDash/collision/CollisionHandler.java
  source/core/src/main/com/csse3200/game/components/minigames/birdieDash/controller/BirdieDashController.java
  source/core/src/main/com/csse3200/game/components/minigames/birdieDash/controller/KeyboardBirdInputComponent.java
  source/core/src/main/com/csse3200/game/components/minigames/birdieDash/entities/Bird.java
  source/core/src/main/com/csse3200/game/components/minigames/birdieDash/entities/Coin.java
  source/core/src/main/com/csse3200/game/components/minigames/birdieDash/entities/Pipe.java
  source/core/src/main/com/csse3200/game/components/minigames/birdieDash/entities/Spike.java
  source/core/src/main/com/csse3200/game/components/minigames/birdieDash/rendering/BackgroundRenderer.java
  source/core/src/main/com/csse3200/game/components/minigames/birdieDash/rendering/BirdRenderer.java
  source/core/src/main/com/csse3200/game/components/minigames/birdieDash/rendering/CoinRenderer.java
  source/core/src/main/com/csse3200/game/components/minigames/birdieDash/rendering/PipeRenderer.java
  source/core/src/main/com/csse3200/game/components/minigames/birdieDash/rendering/SpikeRenderer.java
  source/core/src/main/com/csse3200/game/components/minigames/snake/AssetPaths.java
  source/core/src/main/com/csse3200/game/components/minigames/snake/rendering/SnakeGameRenderer.java
  source/core/src/main/com/csse3200/game/components/tasks/ItemProximityTask.java
  source/core/src/main/com/csse3200/game/screens/BirdieDashScreen.java
  source/core/src/main/com/csse3200/game/screens/EndMiniGameScreen.java
  source/core/src/main/com/csse3200/game/screens/MiniGameMenuScreen.java
  source/core/src/main/com/csse3200/game/screens/SnakeScreen.java
  source/core/src/main/com/csse3200/game/ui/minigames/ScoreBoard.java
  source/core/src/test/com/csse3200/game/components/minigames/birdieDash/entities/BirdTest.java
  source/core/src/test/com/csse3200/game/components/minigames/birdieDash/entities/CoinTest.java
  source/core/src/test/com/csse3200/game/components/minigames/birdieDash/entities/PipeTest.java
  source/core/src/test/com/csse3200/game/components/minigames/birdieDash/entities/SpikeTest.java
Labels: Sprint 2, Team 7

#276 Magpie birdie dash minigame integration
  source/core/assets/configs/NPCs.json
  source/core/src/main/com/csse3200/game/ui/DialogueBox.java
  source/core/src/test/com/csse3200/game/entities/factories/NPCFactoryTest.java
Labels: Team 7

#275 3/242 saving inventory
  .gitignore
  saves/quests.json
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/gameover/GameOverActions.java
  source/core/src/main/com/csse3200/game/components/maingame/MainGameActions.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuActions.java
  source/core/src/main/com/csse3200/game/components/player/InventoryComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerInventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/quests/QuestManager.java
  source/core/src/main/com/csse3200/game/components/quests/QuestPopup.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/gamestate/GameState.java
  source/core/src/main/com/csse3200/game/gamestate/data/InventorySave.java
  source/core/src/main/com/csse3200/game/gamestate/data/QuestSave.java
  source/core/src/main/com/csse3200/game/inventory/Inventory.java
  source/core/src/main/com/csse3200/game/inventory/items/food/Foods.java
  source/core/src/main/com/csse3200/game/overlays/PauseDisplay.java
  source/core/src/test/com/csse3200/game/components/player/PlayerInventoryDisplayTest.java
  source/core/src/test/com/csse3200/game/inventory/InventoryTest.java
Labels: Sprint 2, Team 3, Team 5

#289 Team 2 Adding Transition to Combat Screen for Enemy NPCs
  source/core/assets/configs/ForestGameAreaConfigs/entitySpawn.json
  source/core/assets/images/bear_idle.png
  source/core/assets/images/transitionBg.jpg
  source/core/assets/images/transitionChickenBg.jpg
  source/core/assets/images/white_pixel.png
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/areas/CombatArea.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/quests/QuestManager.java
  source/core/src/main/com/csse3200/game/entities/Entity.java
  source/core/src/main/com/csse3200/game/entities/factories/EnemyFactory.java
  source/core/src/main/com/csse3200/game/rendering/AnimationRenderComponent.java
  source/core/src/main/com/csse3200/game/screens/EnemyCutsceneScreen.java
Labels: Sprint 2, Team 2

#295 Added basic player information saving and loading
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/animal/AnimalSelectionActions.java
  source/core/src/main/com/csse3200/game/components/gamearea/GameAreaDisplay.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuActions.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/gamestate/GameState.java
  source/core/src/main/com/csse3200/game/gamestate/data/PlayerSave.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
Labels: Team 1, Team 5, Collaboration Ticket

#262 Added options functionality for the dialogues
  source/core/assets/configs/NPCs.json
  source/core/assets/images/blue-b-hover.png
  source/core/assets/images/blue-button.png
  source/core/src/main/com/csse3200/game/components/player/PlayerInventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/tasks/ItemProximityTask.java
  source/core/src/main/com/csse3200/game/components/tasks/PauseTask.java
  source/core/src/main/com/csse3200/game/entities/DialogueBoxService.java
  source/core/src/main/com/csse3200/game/entities/configs/BaseFriendlyEntityConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/ui/DialogueBox.java
  source/core/src/test/com/csse3200/game/entities/DialogueBoxServiceTest.java
  source/core/src/test/com/csse3200/game/entities/factories/NPCFactoryTest.java
Labels: Sprint 2, Team 4

#302 Fixed bug which crashes game after Combat Win
  source/core/src/main/com/csse3200/game/components/combat/CombatManager.java
Labels: bug, Sprint 2, Team 9

#297 Added Audio testing, Settings menu and updated loading screen display + Refactoring
  assets/wiki/screenshot/login/LoginScreenShot.png
  assets/wiki/screenshot/login/RegisterScreenShot.png
  source/core/assets/configs/ForestGameAreaConfigs/entitySpawn.json
  source/core/assets/images/ButtonsMain/BlankLarge.png
  source/core/assets/images/ButtonsMain/BlankSmall.png
  source/core/assets/images/ButtonsMain/Writing UI.png
  source/core/assets/images/animal/loadingbg.png
  source/core/assets/images/bear_idle.png
  source/core/assets/images/transitionBg.jpg
  source/core/assets/images/transitionChickenBg.jpg
  source/core/assets/images/white_pixel.png
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/areas/CombatArea.java
  source/core/src/main/com/csse3200/game/components/login/LoginRegisterDisplay.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/mainmenu/Slides.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/quests/QuestManager.java
  source/core/src/main/com/csse3200/game/components/settingsmenu/SettingsMenuWrapper.java
  source/core/src/main/com/csse3200/game/components/settingsmenu/UserSettings.java
  source/core/src/main/com/csse3200/game/entities/Entity.java
  source/core/src/main/com/csse3200/game/entities/factories/EnemyFactory.java
  source/core/src/main/com/csse3200/game/overlays/Overlay.java
  source/core/src/main/com/csse3200/game/overlays/PauseDisplay.java
  source/core/src/main/com/csse3200/game/overlays/SettingsOverlay.java
  source/core/src/main/com/csse3200/game/rendering/AnimationRenderComponent.java
  source/core/src/main/com/csse3200/game/screens/EnemyCutsceneScreen.java
  source/core/src/main/com/csse3200/game/screens/LoadingScreen.java
  source/core/src/main/com/csse3200/game/screens/MainMenuScreen.java
  source/core/src/main/com/csse3200/game/screens/PausableScreen.java
  source/core/src/main/com/csse3200/game/services/AudioManager.java
  source/core/src/test/com/csse3200/game/services/AudioManagerTest.java
  source/desktop/src/com/csse3200/game/desktop/DesktopLauncher.java
Labels: Sprint 2, Team 6

#303 [Team 1] Combat Quick-Time Events
  source/core/assets/images/quicktimeevent/paws.atlas
  source/core/assets/images/quicktimeevent/paws.png
  source/core/assets/images/quicktimeevent/white_background.png
  source/core/assets/sounds/victory.mp3
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/components/combat/KeyboardCombatInputComponent.java
  source/core/src/main/com/csse3200/game/components/combat/TouchCombatInputComponent.java
  source/core/src/main/com/csse3200/game/components/combat/quicktimeevent/QuickTimeEvent.java
  source/core/src/main/com/csse3200/game/components/combat/quicktimeevent/QuickTimeEventActions.java
  source/core/src/main/com/csse3200/game/components/combat/quicktimeevent/QuickTimeEventDisplay.java
  source/core/src/main/com/csse3200/game/input/InputFactory.java
  source/core/src/main/com/csse3200/game/input/KeyboardInputFactory.java
  source/core/src/main/com/csse3200/game/input/TouchInputFactory.java
  source/core/src/main/com/csse3200/game/screens/QuickTimeEventScreen.java
  source/core/src/test/com/csse3200/game/components/combat/quicktimeevent/QuickTimeEventTest.java
Labels: Sprint 2, Team 1

#292 Intro Story
  source/core/assets/images/Story/DogStory3.png
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/components/animal/AnimalSelectionActions.java
  source/core/src/main/com/csse3200/game/components/story/StoryActions.java
  source/core/src/main/com/csse3200/game/components/story/StoryDisplay.java
  source/core/src/main/com/csse3200/game/screens/StoryScreen.java
Labels: enhancement, Task Ticket, Team 9

#306 9/ Post Combat
  source/core/assets/configs/achievements.json
  source/core/assets/configs/endgameStats.json
  source/core/assets/images/logbook/lb-bg.png
  source/core/assets/images/logbook/lb-blue-btn-pressed.png
  source/core/assets/images/logbook/lb-blue-btn.png
  source/core/assets/images/logbook/lb-blue-tab.png
  source/core/assets/images/logbook/lb-red-btn-pressed.png
  source/core/assets/images/logbook/lb-red-btn.png
  source/core/assets/images/logbook/lb-red-tab.png
  source/core/assets/images/logbook/lb-yellow-btn-pressed.png
  source/core/assets/images/logbook/lb-yellow-btn.png
  source/core/assets/images/logbook/lb-yellow-tab.png
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/animal/AnimalSelectionDisplay.java
  source/core/src/main/com/csse3200/game/components/combat/CombatActions.java
  source/core/src/main/com/csse3200/game/components/combat/CombatEnvironmentDisplay.java
  source/core/src/main/com/csse3200/game/components/combat/CombatExitDisplay.java
  source/core/src/main/com/csse3200/game/components/combat/CombatManager.java
  source/core/src/main/com/csse3200/game/components/maingame/MainGameActions.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuActions.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/player/PlayerStatsDisplay.java
  source/core/src/main/com/csse3200/game/components/quests/AchievementDisplay.java
  source/core/src/main/com/csse3200/game/components/quests/DialogueKey.java
  source/core/src/main/com/csse3200/game/components/quests/QuestHidden.java
  source/core/src/main/com/csse3200/game/components/quests/QuestManager.java
  source/core/src/main/com/csse3200/game/components/stats/Stat.java
  source/core/src/main/com/csse3200/game/components/stats/StatDisplay.java
  source/core/src/main/com/csse3200/game/components/stats/StatManager.java
  source/core/src/main/com/csse3200/game/components/stats/StatSaveManager.java
  source/core/src/main/com/csse3200/game/entities/Entity.java
  source/core/src/main/com/csse3200/game/entities/configs/BaseFriendlyEntityConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/EnemyFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/inventory/items/food/Foods.java
  source/core/src/main/com/csse3200/game/screens/CombatScreen.java
  source/core/src/main/com/csse3200/game/screens/EndGameStatsScreen.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/services/ServiceContainer.java
  source/core/src/test/com/csse3200/game/components/CombatStatsComponentTest.java
  source/core/src/test/com/csse3200/game/components/TouchAttackComponentTest.java
  source/core/src/test/com/csse3200/game/components/quests/QuestHiddenTest.java
  source/core/src/test/com/csse3200/game/components/quests/QuestManagerTest.java
  source/core/src/test/com/csse3200/game/components/stats/StatTest.java
  source/core/src/test/com/csse3200/game/inventory/items/AbstractFoodTest.java
  source/core/src/test/com/csse3200/game/inventory/items/FoodItemTest.java
  source/core/src/test/com/csse3200/game/inventory/items/TimedUseItemTest.java
Labels: Sprint 2, Team 9

#307 [Team 1] Animal stats, sounds and movement
  saves/quests.json
  source/core/src/main/com/csse3200/game/components/animal/AnimalSelectionActions.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/overlays/Overlay.java
  source/core/src/main/com/csse3200/game/overlays/PlayerStatsDisplay2.java
  source/core/src/main/com/csse3200/game/overlays/PlayerStatsOverlay.java
  source/core/src/main/com/csse3200/game/screens/PausableScreen.java
  source/core/src/main/com/csse3200/game/ui/PopUpDialogBox/PopUpHelper.java
  source/core/src/main/com/csse3200/game/ui/PopUpDialogBox/PopupDialogBox.java
  source/core/src/test/com/csse3200/game/components/animal/AnimalSelectionActionsTest.java
  source/core/src/test/com/csse3200/game/components/audio/DogSoundPlayerTest.java
Labels: Sprint 2, Team 1

#310 [Team 2] New enemy branch implementing monkey and bear
  source/core/assets/configs/ForestGameAreaConfigs/entitySpawn.json
  source/core/assets/configs/ForestGameAreaConfigs/textures.json
  source/core/assets/configs/enemyNPCs.json
  source/core/assets/images/banana.atlas
  source/core/assets/images/banana.png
  source/core/assets/images/bear.atlas
  source/core/assets/images/bear.png
  source/core/assets/images/bear_idle.png
  source/core/assets/images/chicken.atlas
  source/core/assets/images/chicken.png
  source/core/assets/images/frog.atlas
  source/core/assets/images/monkey.atlas
  source/core/src/main/com/csse3200/game/areas/CombatArea.java
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java.autosave
  source/core/src/main/com/csse3200/game/areas/ForestGameAreaConfigs/EntitySpawnConfig.java
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/components/ProjectileAttackComponent.java
  source/core/src/main/com/csse3200/game/components/ProximityComponent.java
  source/core/src/main/com/csse3200/game/components/npc/BananaAnimationController.java
  source/core/src/main/com/csse3200/game/components/npc/BearAnimationController.java
  source/core/src/main/com/csse3200/game/components/npc/ChickenAnimationController.java
  source/core/src/main/com/csse3200/game/components/npc/FrogAnimationController.java
  source/core/src/main/com/csse3200/game/components/npc/MonkeyAnimationController.java
  source/core/src/main/com/csse3200/game/components/tasks/ProjectileMovementTask.java
  source/core/src/main/com/csse3200/game/components/tasks/ShootTask.java
  source/core/src/main/com/csse3200/game/components/tasks/SpecialWanderTask.java
  source/core/src/main/com/csse3200/game/components/tasks/WanderTask.java
  source/core/src/main/com/csse3200/game/entities/Entity.java
  source/core/src/main/com/csse3200/game/entities/configs/NPCConfigs.java
  source/core/src/main/com/csse3200/game/entities/factories/EnemyFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/ProjectileFactory.java
  source/core/src/main/com/csse3200/game/physics/PhysicsLayer.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/services/ServiceLocator.java
  source/core/src/test/com/csse3200/game/components/ProjectileAttackComponentTest.java
  source/core/src/test/com/csse3200/game/components/tasks/ShootTaskTest.java
  source/core/src/test/com/csse3200/game/entities/factories/EnemyFactoryTest.java
  source/core/src/test/com/csse3200/game/entities/factories/ProjectileFactoryTest.java
  source/core/src/test/com/csse3200/game/inventory/items/TimedUseItemTest.java
Labels: Sprint 2, Team 2

#312 5-logbook
  source/.gitignore
  source/core/assets/configs/achievements.json
  source/core/assets/images/ButtonsMain/logbook1.png
  source/core/assets/images/logbook/icons/bird-bronze.png
  source/core/assets/images/logbook/icons/bird-gold.png
  source/core/assets/images/logbook/icons/bird-silver.png
  source/core/assets/images/logbook/icons/bronze-medal.png
  source/core/assets/images/logbook/icons/chicken.png
  source/core/assets/images/logbook/icons/first-steps.png
  source/core/assets/images/logbook/icons/frog.png
  source/core/assets/images/logbook/icons/gold-medal.png
  source/core/assets/images/logbook/icons/monkey.png
  source/core/assets/images/logbook/icons/silver-medal.png
  source/core/assets/images/logbook/icons/snake-bronze.png
  source/core/assets/images/logbook/icons/snake-gold.png
  source/core/assets/images/logbook/icons/snake-silver.png
  source/core/assets/images/logbook/lb-exit.png
  source/core/assets/sounds/logbook/select_004.ogg
  source/core/assets/sounds/logbook/select_005.ogg
  source/core/src/main/com/csse3200/game/components/combat/CombatActions.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/quests/Achievement.java
  source/core/src/main/com/csse3200/game/components/quests/AchievementDisplay.java
  source/core/src/main/com/csse3200/game/components/quests/AchievementManager.java
  source/core/src/main/com/csse3200/game/components/quests/LogButton.java
  source/core/src/main/com/csse3200/game/components/quests/QuestManager.java
  source/core/src/main/com/csse3200/game/components/quests/TabButton.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/screens/EndMiniGameScreen.java
  source/core/src/main/com/csse3200/game/services/ResourceService.java
  source/core/src/test/com/csse3200/game/components/quests/AchievementManagerTest.java
  source/core/src/test/com/csse3200/game/components/quests/AchievementTest.java
  source/core/src/test/com/csse3200/game/components/quests/InventoryTest.java
  source/core/src/test/com/csse3200/game/components/quests/QuestManagerTest.java
Labels: Sprint 2, Team 5

#288 5/Achievement Popup
  source/core/assets/configs/ForestGameAreaConfigs/sounds.json
  source/core/assets/images/logbook-popup.png
  source/core/assets/images/logbook/icons/first-steps.png
  source/core/assets/images/logbook/lb-bg.png
  source/core/assets/images/logbook/lb-blue-btn-pressed.png
  source/core/assets/images/logbook/lb-blue-btn.png
  source/core/assets/images/logbook/lb-blue-tab.png
  source/core/assets/images/logbook/lb-exit.png
  source/core/assets/images/logbook/lb-red-btn-pressed.png
  source/core/assets/images/logbook/lb-red-btn.png
  source/core/assets/images/logbook/lb-red-tab.png
  source/core/assets/images/logbook/lb-yellow-btn-pressed.png
  source/core/assets/images/logbook/lb-yellow-btn.png
  source/core/assets/images/logbook/lb-yellow-tab.png
  source/core/assets/sounds/achievement-sound.mp3
  source/core/assets/sounds/logbook/select_004.ogg
  source/core/assets/sounds/logbook/select_005.ogg
  source/core/src/main/com/csse3200/game/components/quests/AchievementDisplay.java
  source/core/src/main/com/csse3200/game/components/quests/AchievementPopup.java
  source/core/src/main/com/csse3200/game/components/quests/QuestHidden.java
  source/core/src/main/com/csse3200/game/components/quests/QuestManager.java
  source/core/src/main/com/csse3200/game/components/quests/QuestPopup.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/inventory/items/food/Foods.java
  source/core/src/main/com/csse3200/game/services/ResourceService.java
  source/core/src/test/com/csse3200/game/components/quests/QuestHiddenTest.java
  source/core/src/test/com/csse3200/game/components/quests/QuestManagerTest.java
Labels: Sprint 2, Team 5

#309 BUG FIX: Game crashes as 'saves/endgameStats.json' does not exist
  defaultsaves/inventory.json
  defaultsaves/player.json
  defaultsaves/quests.json
  defaultsaves/stats.json
  source/core/assets/configs/defaultsaves/inventory.json
  source/core/assets/configs/defaultsaves/player.json
  source/core/assets/configs/defaultsaves/quests.json
  source/core/assets/configs/defaultsaves/stats.json
  source/core/assets/defaultsaves/inventory.json
  source/core/assets/defaultsaves/player.json
  source/core/assets/defaultsaves/quests.json
  source/core/assets/defaultsaves/stats.json
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuActions.java
  source/core/src/main/com/csse3200/game/components/quests/QuestManager.java
  source/core/src/main/com/csse3200/game/components/stats/Stat.java
  source/core/src/main/com/csse3200/game/components/stats/StatDisplay.java
  source/core/src/main/com/csse3200/game/components/stats/StatManager.java
  source/core/src/main/com/csse3200/game/components/stats/StatSaveManager.java
  source/core/src/main/com/csse3200/game/gamestate/GameState.java
  source/core/src/main/com/csse3200/game/gamestate/data/StatSave.java
  source/core/src/main/com/csse3200/game/inventory/Inventory.java
  source/core/src/test/com/csse3200/game/components/stats/StatTest.java
Labels: bug, Sprint 2, Team 9

#317 4/ Implemented entity conversion
  source/core/assets/configs/ForestGameAreaConfigs/textures.json
  source/core/assets/configs/NPCs.json
  source/core/assets/configs/enemyNPCs.json
  source/core/src/main/com/csse3200/game/components/combat/CombatActions.java
  source/core/src/main/com/csse3200/game/entities/Entity.java
  source/core/src/main/com/csse3200/game/entities/EntityConverter.java
  source/core/src/main/com/csse3200/game/entities/configs/BaseEntityConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/BaseFriendlyEntityConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/NPCConfigs.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/physics/components/PhysicsMovementComponent.java
  source/core/src/test/com/csse3200/game/entities/EntityConverterTest.java
  source/core/src/test/com/csse3200/game/entities/factories/EnemyFactoryTest.java
Labels: Task Ticket, Sprint 2, Team 4

#337 4/dialogue box bugs
  source/core/assets/images/blue-bar.png
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/quests/QuestManager.java
  source/core/src/main/com/csse3200/game/components/tasks/ItemProximityTask.java
  source/core/src/main/com/csse3200/game/components/tasks/PauseTask.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/input/InputFactory.java
  source/core/src/main/com/csse3200/game/input/KeyboardInputFactory.java
  source/core/src/main/com/csse3200/game/input/TouchInputFactory.java
  source/core/src/main/com/csse3200/game/rendering/Renderer.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/services/DialogueBoxService.java
  source/core/src/main/com/csse3200/game/services/ServiceContainer.java
  source/core/src/main/com/csse3200/game/services/ServiceLocator.java
  source/core/src/main/com/csse3200/game/ui/dialoguebox/DialogueBox.java
  source/core/src/main/com/csse3200/game/ui/dialoguebox/KeyboardDialogueBoxInputComponent.java
  source/core/src/test/com/csse3200/game/components/tasks/ItemProximityTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/PauseTaskTest.java
  source/core/src/test/com/csse3200/game/entities/DialogueBoxServiceTest.java
  source/core/src/test/com/csse3200/game/entities/factories/NPCFactoryTest.java
  source/core/src/test/com/csse3200/game/ui/dialoguebox/KeyboardDialogueBoxInputComponentTest.java
Labels: bug, Sprint 3, Team 4

#372 Updated JavaDoc
  source/core/src/main/com/csse3200/game/components/tasks/AvoidTask.java
  source/core/src/main/com/csse3200/game/ui/dialoguebox/DialogueBox.java
Labels: bug

#379 Maze generation and integration with fish npc
  saves/quests.json
  source/build.gradle
  source/core/assets/configs/NPCs.json
  source/core/assets/images/minigames/spawn.png
  source/core/assets/images/minigames/wall.png
  source/core/assets/images/minigames/water.png
  source/core/assets/minigameMaze/MazeOne.txt
  source/core/assets/minigameMaze/TestMaze.txt
  source/core/assets/minigameMaze/expanded_maze.txt
  source/core/assets/minigameMaze/maze2.txt
  source/core/assets/minigameMaze/maze5.txt
  source/core/assets/minigameMaze/maze6.txt
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/components/minigames/Direction.java
  source/core/src/main/com/csse3200/game/components/minigames/maze/MazeAssetPaths.java
  source/core/src/main/com/csse3200/game/components/minigames/maze/MazeGame.java
  source/core/src/main/com/csse3200/game/components/minigames/maze/mazegrid/MazeCell.java
  source/core/src/main/com/csse3200/game/components/minigames/maze/mazegrid/MazeGrid.java
  source/core/src/main/com/csse3200/game/components/minigames/maze/mazegrid/Spawn.java
  source/core/src/main/com/csse3200/game/components/minigames/maze/mazegrid/Wall.java
  source/core/src/main/com/csse3200/game/components/minigames/maze/mazegrid/Water.java
  source/core/src/main/com/csse3200/game/components/minigames/maze/rendering/MazeGridRenderer.java
  source/core/src/main/com/csse3200/game/components/minigames/snake/AssetPaths.java
  source/core/src/main/com/csse3200/game/screens/EndMiniGameScreen.java
  source/core/src/main/com/csse3200/game/screens/MazeGameScreen.java
  source/core/src/main/com/csse3200/game/screens/MiniGameMenuScreen.java
  source/core/src/main/com/csse3200/game/ui/dialoguebox/DialogueBox.java
  source/core/src/test/com/csse3200/game/components/minigames/maze/MazeGameTest.java
  source/core/src/test/com/csse3200/game/components/minigames/maze/mazegrid/MazeGridTest.java
  source/core/src/test/com/csse3200/game/entities/factories/NPCFactoryTest.java
Labels: Sprint 3, Team 7

#388 Added General Functionality
  hs_err_pid9540.log
  source/core/assets/flat-earth/skin/flat-earth-ui.json
  source/core/assets/images/ButtonsMain/White Alphabet.png
  source/core/assets/images/Croc2.png
  source/core/assets/images/CustomCursor.png
  source/core/assets/images/NightToggle.png
  source/core/assets/images/Story/CrocStory1.png
  source/core/assets/images/Story/CrocStory2.png
  source/core/assets/images/Story/CrocStory3.png
  source/core/assets/images/Story/DogStory1.png
  source/core/assets/images/Story/DogStory2.png
  source/core/assets/images/animal/moon.png
  source/core/assets/images/minigames/snakebodybent.png
  source/core/assets/images/minigames/snakebodyhorizontal.png
  source/core/assets/images/minigames/snakebodyvertical.png
  source/core/assets/images/minigames/snakehead.png
  source/core/assets/images/notification/BlueNotif.png
  source/core/assets/images/notification/GreenNotif.png
  source/core/assets/images/notification/RedNotif.png
  source/core/assets/images/transitionChickenBg.jpg
  source/core/assets/images/white_pixel.png
  source/core/assets/libs/client-sdk-0.224.240830.jar
  source/core/assets/libs/gson-2.8.0.jar
  source/core/assets/shaders/nightmode.frag
  source/core/assets/shaders/nightmode.vert
  source/core/assets/test/achievements.json
  source/core/build.gradle
  source/core/src/main/com/csse3200/game/areas/CombatArea.java
  source/core/src/main/com/csse3200/game/components/loading/LoadingDisplay.java
  source/core/src/main/com/csse3200/game/components/loading/MoonActor.java
  source/core/src/main/com/csse3200/game/components/login/LoginRegisterDisplay.java
  source/core/src/main/com/csse3200/game/components/login/PlayFab.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/csse3200/game/rendering/AnimationRenderComponent.java
  source/core/src/main/com/csse3200/game/screens/LoadingScreen.java
  source/core/src/main/com/csse3200/game/services/NotifManager.java
  source/core/src/test/com/csse3200/game/components/loading/LoadingDisplayTest.java
  source/core/src/test/com/csse3200/game/components/login/PlayFabTest.java
Labels: Sprint 3, Team 6

#399 Fixed bug where exiting and going back into game caused crash
  source/core/src/main/com/csse3200/game/areas/MapHandler.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
Labels: bug, Team 3

#391 Chunk tile count function
  source/core/assets/configs/ForestGameAreaConfigs/forestTiles.json
  source/core/assets/configs/ForestGameAreaConfigs/textures.json
  source/core/src/main/com/csse3200/game/areas/ForestGameAreaConfigs/ForestTileConfig.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainChunk.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainComponent.java
  source/core/src/test/com/csse3200/game/areas/terrain/TerrainChunkTest.java
Labels: Team 8

#406 Updated CombatInventoryDisplay, Initialisation, and Logic
  source/core/src/main/com/csse3200/game/components/combat/CombatActions.java
  source/core/src/main/com/csse3200/game/components/combat/CombatButtonDisplay.java
  source/core/src/main/com/csse3200/game/components/combat/CombatInventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/player/PlayerInventoryDisplay.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/screens/CombatScreen.java
Labels: enhancement, Sprint 3, Team 3, Team 10, Collaboration Ticket

#401 New DialogueBox feature for CombatScreen
  source/core/src/main/com/csse3200/game/components/combat/CombatActions.java
  source/core/src/main/com/csse3200/game/components/combat/CombatButtonDisplay.java
  source/core/src/main/com/csse3200/game/components/combat/CombatEnvironmentDisplay.java
  source/core/src/main/com/csse3200/game/components/combat/CombatManager.java
  source/core/src/main/com/csse3200/game/screens/CombatScreen.java
Labels: Sprint 3, Team 10

#425 Items as a Move in Combat
  source/core/src/main/com/csse3200/game/components/combat/CombatActions.java
  source/core/src/main/com/csse3200/game/components/combat/CombatButtonDisplay.java
  source/core/src/main/com/csse3200/game/components/combat/CombatInventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/combat/CombatManager.java
  source/core/src/main/com/csse3200/game/components/inventory/PlayerInventoryDisplay.java
  source/core/src/main/com/csse3200/game/screens/CombatScreen.java
Labels: enhancement, Sprint 3, Team 3, Team 10, Collaboration Ticket

#421 Drag And Drop and Subscripts Added
  source/core/src/main/com/csse3200/game/components/inventory/InventoryComponent.java
  source/core/src/main/com/csse3200/game/components/inventory/PlayerInventoryDisplay.java
  source/core/src/main/com/csse3200/game/inventory/Inventory.java
  source/core/src/main/com/csse3200/game/inventory/InventoryInterface.java
  source/core/src/test/com/csse3200/game/inventory/InventoryTest.java
Labels: Task Ticket, Feature Ticket, Sprint 3, Team 3

#426 3/343 allow inventory access during combat
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/combat/CombatActions.java
  source/core/src/main/com/csse3200/game/components/combat/CombatButtonDisplay.java
  source/core/src/main/com/csse3200/game/components/combat/CombatInventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/combat/CombatManager.java
  source/core/src/main/com/csse3200/game/components/combat/CombatStatsDisplay.java
  source/core/src/main/com/csse3200/game/components/combat/move/CombatMoveComponent.java
  source/core/src/main/com/csse3200/game/components/combat/move/ItemMove.java
  source/core/src/main/com/csse3200/game/components/inventory/PlayerInventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/tasks/TimedUseItemTask.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/inventory/items/TimedUseItem.java
  source/core/src/main/com/csse3200/game/inventory/items/potions/AttackPotion.java
  source/core/src/main/com/csse3200/game/inventory/items/potions/DefensePotion.java
  source/core/src/main/com/csse3200/game/inventory/items/potions/SpeedPotion.java
  source/core/src/main/com/csse3200/game/screens/CombatScreen.java
  source/core/src/test/com/csse3200/game/inventory/items/TimedUseItemTest.java
Labels: Sprint 3, Team 3, Team 10, Collaboration Ticket

#412 5 achievements 3
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/quests/AchievementDisplay.java
Labels: Sprint 3, Team 5

#424 Implement Day Night Cycle and Glow Around NPCs
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/entities/factories/EnemyFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/ObstacleFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/lighting/DayNightCycle.java
  source/core/src/main/com/csse3200/game/lighting/LightingEngine.java
  source/core/src/main/com/csse3200/game/lighting/LightingService.java
  source/core/src/main/com/csse3200/game/lighting/LightingUtils.java
  source/core/src/main/com/csse3200/game/lighting/components/FadeLightsDayTimeComponent.java
  source/core/src/main/com/csse3200/game/lighting/components/LightingComponent.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/test/com/csse3200/game/entities/EntityConverterTest.java
  source/core/src/test/com/csse3200/game/entities/factories/EnemyFactoryTest.java
  source/core/src/test/com/csse3200/game/entities/factories/NPCFactoryTest.java
  source/core/src/test/com/csse3200/game/lighting/DayNightCycleTest.java
  source/core/src/test/com/csse3200/game/lighting/LightingEngineTest.java
  source/core/src/test/com/csse3200/game/lighting/LightingServiceTest.java
  source/core/src/test/com/csse3200/game/lighting/components/LightingComponentTest.java
Labels: Team 6, Team 7, Collaboration Ticket

#444 Item Drop Upon Talking To Cows/Fish
  source/core/assets/configs/ForestGameAreaConfigs/textures.json
  source/core/assets/configs/NPCs.json
  source/core/assets/images/foodtextures/Milk.png
  source/core/assets/images/foodtextures/Sushi.png
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/tasks/PauseTask.java
  source/core/src/main/com/csse3200/game/entities/configs/BaseFriendlyEntityConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/ItemFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/inventory/items/food/Foods.java
  source/core/src/test/com/csse3200/game/inventory/items/FoodItemTest.java
Labels: Team 3, Team 4, Collaboration Ticket
