Repository UQcsse3200/2024-studio-2, pull requests merged in 2024-08, with the labels that each got.

#25 Save Handler and Game State
  source/core/src/main/com/csse3200/game/files/FileLoader.java
  source/core/src/main/com/csse3200/game/gamestate/EnvironmentVariables.java
  source/core/src/main/com/csse3200/game/gamestate/GameState.java
  source/core/src/main/com/csse3200/game/gamestate/SaveHandler.java
  source/core/src/test/com/csse3200/game/gamestate/EnvironmentVariablesTest.java
  source/core/src/test/com/csse3200/game/gamestate/GameStateTest.java
  source/core/src/test/com/csse3200/game/gamestate/SaveHandlerTest.java
Labels: Team 5

#37 Created abstract classes for ConsumableItem #3 #27
  source/core/src/main/com/csse3200/game/inventory/items/ConsumableItem.java
  source/core/src/main/com/csse3200/game/inventory/items/exceptions/ConsumedException.java
  source/core/src/test/com/csse3200/game/inventory/items/ConsumableItemTest.java
Labels: Team 3

#43 Version 1 of Inventory (#19) for #3
  source/core/src/main/com/csse3200/game/inventory/Inventory.java
  source/core/src/main/com/csse3200/game/inventory/InventoryInterface.java
  source/core/src/test/com/csse3200/game/inventory/InventoryTest.java
Labels: Team 3

#113 Team 5: Added JSON saving and loading functionality
  .gitignore
  source/core/src/main/com/csse3200/game/files/FileLoader.java
  source/core/src/main/com/csse3200/game/gamestate/Achievements.java
  source/core/src/main/com/csse3200/game/gamestate/GameState.java
  source/core/src/main/com/csse3200/game/gamestate/SaveHandler.java
  source/core/src/main/com/csse3200/game/gamestate/data/WorldState.java
  source/core/src/test/com/csse3200/game/gamestate/EnvironmentVariablesTest.java
  source/core/src/test/com/csse3200/game/gamestate/GameStateTest.java
  source/core/src/test/com/csse3200/game/gamestate/SaveHandlerTest.java
Labels: Sprint 1, Team 5

#120 3/105 place items in map
  source/core/assets/configs/player.json
  source/core/assets/images/Healthpotion.png
  source/core/assets/images/foodtextures/apple.png
  source/core/assets/images/potiontexture/attack.png
  source/core/assets/images/potiontexture/defence.png
  source/core/assets/images/potiontexture/health.png
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/player/InventoryComponent.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerInventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/tasks/ItemProximityTask.java
  source/core/src/main/com/csse3200/game/entities/configs/PlayerConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/ItemFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/events/EventHandler.java
  source/core/src/main/com/csse3200/game/inventory/Inventory.java
  source/core/src/main/com/csse3200/game/inventory/items/AbstractItem.java
  source/core/src/main/com/csse3200/game/inventory/items/ConsumableItem.java
  source/core/src/main/com/csse3200/game/inventory/items/effects/AbstractEffect.java
  source/core/src/main/com/csse3200/game/inventory/items/effects/feeding/FeedEffect.java
  source/core/src/main/com/csse3200/game/inventory/items/effects/healing/HealEffect.java
  source/core/src/main/com/csse3200/game/inventory/items/food/AbstractFood.java
  source/core/src/main/com/csse3200/game/inventory/items/food/Foods.java
  source/core/src/main/com/csse3200/game/inventory/items/potions/AbstractPotion.java
  source/core/src/main/com/csse3200/game/inventory/items/potions/healingpotion/HealingPotion.java
  source/core/src/main/com/csse3200/game/ui/ChatOverlay.java
  source/core/src/test/com/csse3200/game/components/player/InventoryComponentTest.java
  source/core/src/test/com/csse3200/game/components/player/KeyboardPlayerInputComponentTest.java
  source/core/src/test/com/csse3200/game/components/player/PlayerInventoryDisplayTest.java
  source/core/src/test/com/csse3200/game/components/tasks/ItemProximityTaskTest.java
  source/core/src/test/com/csse3200/game/inventory/InventoryTest.java
  source/core/src/test/com/csse3200/game/inventory/items/AbstractFoodTest.java
  source/core/src/test/com/csse3200/game/inventory/items/AbstractItemTest.java
  source/core/src/test/com/csse3200/game/inventory/items/ConsumableItemTest.java
  source/core/src/test/com/csse3200/game/inventory/items/effects/AbstractEffectTest.java
  source/core/src/test/com/csse3200/game/inventory/items/potions/AbstractPotionTest.java
Labels: Task Ticket, Team 3

#125 3 inventory and items
  source/core/assets/images/Healthpotion.png
  source/core/assets/images/foodtextures/apple.png
  source/core/assets/images/foodtextures/candy.png
  source/core/assets/images/foodtextures/carrot.png
  source/core/assets/images/foodtextures/chicken_leg.png
  source/core/assets/images/foodtextures/download.png
  source/core/assets/images/foodtextures/meat.png
  source/core/assets/images/potiontexture/attack.png
  source/core/assets/images/potiontexture/defence.png
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/player/InventoryComponent.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerInventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/tasks/ItemProximityTask.java
  source/core/src/main/com/csse3200/game/entities/factories/ItemFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/events/EventHandler.java
  source/core/src/main/com/csse3200/game/inventory/Inventory.java
  source/core/src/main/com/csse3200/game/inventory/InventoryInterface.java
  source/core/src/main/com/csse3200/game/inventory/items/AbstractItem.java
  source/core/src/main/com/csse3200/game/inventory/items/ConsumableItem.java
  source/core/src/main/com/csse3200/game/inventory/items/ItemUsageContext.java
  source/core/src/main/com/csse3200/game/inventory/items/effects/AbstractEffect.java
  source/core/src/main/com/csse3200/game/inventory/items/effects/feeding/FeedEffect.java
  source/core/src/main/com/csse3200/game/inventory/items/effects/healing/HealEffect.java
  source/core/src/main/com/csse3200/game/inventory/items/exceptions/ConsumedException.java
  source/core/src/main/com/csse3200/game/inventory/items/food/AbstractFood.java
  source/core/src/main/com/csse3200/game/inventory/items/food/Foods.java
  source/core/src/main/com/csse3200/game/inventory/items/potions/AbstractPotion.java
  source/core/src/main/com/csse3200/game/inventory/items/potions/healingpotion/HealingPotion.java
  source/core/src/main/com/csse3200/game/screens/SnakeScreen.java
  source/core/src/main/com/csse3200/game/ui/ChatOverlay.java
  source/core/src/test/com/csse3200/game/components/player/InventoryComponentTest.java
  source/core/src/test/com/csse3200/game/components/player/KeyboardPlayerInputComponentTest.java
  source/core/src/test/com/csse3200/game/components/player/PlayerInventoryDisplayTest.java
  source/core/src/test/com/csse3200/game/components/tasks/ItemProximityTaskTest.java
  source/core/src/test/com/csse3200/game/entities/factories/ItemFactoryTest.java
  source/core/src/test/com/csse3200/game/inventory/InventoryTest.java
  source/core/src/test/com/csse3200/game/inventory/items/AbstractFoodTest.java
  source/core/src/test/com/csse3200/game/inventory/items/AbstractItemTest.java
  source/core/src/test/com/csse3200/game/inventory/items/ConsumableItemTest.java
  source/core/src/test/com/csse3200/game/inventory/items/ItemUsageContextTest.java
  source/core/src/test/com/csse3200/game/inventory/items/effects/AbstractEffectTest.java
  source/core/src/test/com/csse3200/game/inventory/items/potions/AbstractPotionTest.java
Labels: Sprint 1, Feature Ticket, Team 3

#129 Player Camera and Unit Tests
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainFactory.java
  source/core/src/main/com/csse3200/game/components/CameraComponent.java
  source/core/src/main/com/csse3200/game/components/CameraZoomComponent.java
  source/core/src/main/com/csse3200/game/components/animal/AnimalSelectionActions.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/rendering/Renderer.java
  source/core/src/test/com/csse3200/game/components/CameraComponentTest.java
  source/core/src/test/com/csse3200/game/components/CameraZoomComponentTest.java
  source/core/src/test/com/csse3200/game/components/animal/AnimalSelectionActionsTest.java
Labels: Sprint 1, Team 1

#131 Remove broken tests
  source/core/src/test/com/csse3200/game/components/player/KeyboardPlayerInputComponentTest.java
Labels: bug

#135 Minigame Snake Game Complete
  source/core/assets/images/BackgroundSplashBasic.png
  source/core/assets/images/img.png
  source/core/assets/images/minigames/Snake.png
  source/core/assets/images/minigames/SnakeIcon.png
  source/core/assets/images/minigames/Underwater_maze.png
  source/core/assets/images/minigames/copysnake.png.jpeg
  source/core/assets/images/minigames/flappybirdicon.png
  source/core/assets/images/minigames/scoreboard.png
  source/core/assets/images/minigames/snakebodybent.png
  source/core/assets/images/minigames/snakebodyhorizontal.png
  source/core/assets/images/minigames/snakebodyvertical.png
  source/core/assets/images/minigames/snakeicon.png
  source/core/assets/images/minigames/underwatermazeicon.png
  source/core/src/main/com/csse3200/game/components/minigame/Direction.java
  source/core/src/main/com/csse3200/game/components/minigame/Grid.java
  source/core/src/main/com/csse3200/game/components/minigame/GridCell.java
  source/core/src/main/com/csse3200/game/components/minigame/MiniGameConstants.java
  source/core/src/main/com/csse3200/game/components/minigame/MiniGameMedals.java
  source/core/src/main/com/csse3200/game/components/minigame/MiniGamesScores.java
  source/core/src/main/com/csse3200/game/components/minigame/snake/Apple.java
  source/core/src/main/com/csse3200/game/components/minigame/snake/AssetPaths.java
  source/core/src/main/com/csse3200/game/components/minigame/snake/Snake.java
  source/core/src/main/com/csse3200/game/components/minigame/snake/SnakeGame.java
  source/core/src/main/com/csse3200/game/components/minigame/snake/SnakeGrid.java
  source/core/src/main/com/csse3200/game/components/minigame/snake/controller/Events.java
  source/core/src/main/com/csse3200/game/components/minigame/snake/controller/SnakeController.java
  source/core/src/main/com/csse3200/game/components/minigame/snake/rendering/AppleRenderer.java
  source/core/src/main/com/csse3200/game/components/minigame/snake/rendering/GridRenderer.java
  source/core/src/main/com/csse3200/game/components/minigame/snake/rendering/SnakeGameRenderer.java
  source/core/src/main/com/csse3200/game/components/minigame/snake/rendering/SnakeRenderer.java
  source/core/src/main/com/csse3200/game/screens/EndSnakeScreen.java
  source/core/src/main/com/csse3200/game/screens/MiniGameMenuScreen.java
  source/core/src/main/com/csse3200/game/screens/SnakeScreen.java
  source/core/src/main/com/csse3200/game/ui/minigame/SnakeScoreBoard.java
  source/core/src/test/com/csse3200/game/components/minigame/MiniGameScoresTest.java
  source/core/src/test/com/csse3200/game/components/minigame/snake/SnakeGameTest.java
  source/core/src/test/com/csse3200/game/components/minigame/snake/SnakeTest.java
Labels: Sprint 1, Team 7

#136 Team 4 submission branch
  source/core/src/main/com/csse3200/game/components/tasks/AvoidTask.java
  source/core/src/main/com/csse3200/game/components/tasks/ChaseTask.java
  source/core/src/main/com/csse3200/game/components/tasks/ItemProximityTask.java
  source/core/src/main/com/csse3200/game/components/tasks/PauseTask.java
  source/core/src/main/com/csse3200/game/entities/EntityChatService.java
  source/core/src/main/com/csse3200/game/entities/configs/BaseEntityConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/CowConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/EagleConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/GhostKingConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/LionConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/SnakeConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/TurtleConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/services/ServiceLocator.java
  source/core/src/main/com/csse3200/game/ui/DialogueBox.java
  source/core/src/test/com/csse3200/game/components/tasks/AvoidTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/PauseTaskTest.java
  source/core/src/test/com/csse3200/game/entities/EntityChatServiceTest.java
  source/core/src/test/com/csse3200/game/entities/factories/NPCFactoryTest.java
Labels: Team 4

#143 11/UI stats branch
  hs_err_pid22624.log
  source/core/assets/hungerbar.atlas
  source/core/assets/hungerbar.png
  source/core/assets/spriteSheets/xpBars.atlas
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/Component.java
  source/core/src/main/com/csse3200/game/components/gamearea/GameAreaDisplay.java
  source/core/src/main/com/csse3200/game/components/player/PlayerStatsDisplay.java
  source/core/src/main/com/csse3200/game/components/player/PlayerStatsDisplayTester.java
  source/core/src/main/com/csse3200/game/entities/configs/BaseEntityConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/events/EventHandler.java
  source/core/src/main/com/csse3200/game/ui/UIComponent.java
Labels: Sprint 1

#132 Splash Screen Update
  assets/wiki/Screens.PNG
  assets/wiki/Screens.png
  source/core/src/main/com/csse3200/game/components/loading/LoadingDisplay.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/settingsmenu/SettingsMenuDisplay.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/screens/MainMenuScreen.java
  source/core/src/main/com/csse3200/game/ui/UIComponent.java
  source/core/src/test/com/csse3200/game/components/loading/LoadingDisplayTest.java
Labels: Sprint 1, Team 6

#144 Splash Screen Fix
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuDisplay.java
Labels: Sprint 1, Team 6

#140 Team 9 - Kanga Boss
  .DS_Store
  assets/.DS_Store
  source/core/assets/images/bag_button.png
  source/core/assets/images/black_bar.png
  source/core/assets/images/final_boss_kangaroo.atlas
  source/core/assets/images/final_boss_kangaroo.png
  source/core/assets/images/final_boss_kangaroo_idle.png
  source/core/assets/images/hit_button.png
  source/core/assets/images/potions_button.png
  source/core/assets/images/vignette.png
  source/core/assets/sounds/heartbeat.mp3
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/ai/tasks/AITaskComponent.java
  source/core/src/main/com/csse3200/game/areas/CombatArea.java
  source/core/src/main/com/csse3200/game/areas/CombatGameArea.java
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/TouchAttackComponent.java
  source/core/src/main/com/csse3200/game/components/combat/CombatActions.java
  source/core/src/main/com/csse3200/game/components/combat/CombatExitDisplay.java
  source/core/src/main/com/csse3200/game/components/maingame/MainGameActions.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuActions.java
  source/core/src/main/com/csse3200/game/components/npc/KangaBossAnimationController.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/player/PlayerStatsDisplay.java
  source/core/src/main/com/csse3200/game/components/stats/Stat.java
  source/core/src/main/com/csse3200/game/components/stats/StatManager.java
  source/core/src/main/com/csse3200/game/components/tasks/AvoidTask.java
  source/core/src/main/com/csse3200/game/components/tasks/ChaseTask.java
  source/core/src/main/com/csse3200/game/components/tasks/MovementTask.java
  source/core/src/main/com/csse3200/game/components/tasks/PauseTask.java
  source/core/src/main/com/csse3200/game/components/tasks/WanderTask.java
  source/core/src/main/com/csse3200/game/entities/Entity.java
  source/core/src/main/com/csse3200/game/entities/configs/KangarooBossConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/NPCConfigs.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/physics/components/PhysicsMovementComponent.java
  source/core/src/main/com/csse3200/game/screens/BossCutsceneScreen.java
  source/core/src/main/com/csse3200/game/screens/CombatScreen.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/utils/math/Vector2Utils.java
  source/core/src/test/com/csse3200/game/Overlays/QuestDisplayTest.java
  source/core/src/test/com/csse3200/game/Overlays/QuestOverlayTest.java
  source/core/src/test/com/csse3200/game/components/TouchAttackComponentTest.java
  source/core/src/test/com/csse3200/game/components/stats/StatTest.java
  source/core/src/test/com/csse3200/game/components/tasks/AvoidTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/ChaseTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/PauseTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/WanderTaskTest.java
  source/core/src/test/com/csse3200/game/entities/factories/NPCFactoryTest.java
Labels: Sprint 1, Team 9
