Repository UQcsse3200/2024-studio-2, pull requests merged in 2024-10, with the labels that each got.

#402 New map design with three areas in one map.
  source/core/assets/configs/ForestGameAreaConfigs/forestTiles.json
  source/core/assets/configs/OceanGameAreaConfigs/entitySpawn.json
  source/core/assets/configs/OceanGameAreaConfigs/sounds.json
  source/core/assets/configs/OceanGameAreaConfigs/textures.json
  source/core/assets/configs/OceanGameAreaConfigs/waterTiles.json
  source/core/assets/images/fog-gate.png
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/MapHandler.java
  source/core/src/main/com/csse3200/game/areas/OceanGameAreaConfigs/EntitySpawnConfig2.java
  source/core/src/main/com/csse3200/game/areas/OceanGameAreaConfigs/OceanGameAreaConfig.java
  source/core/src/main/com/csse3200/game/areas/OceanGameAreaConfigs/OceanMapTiles.java
  source/core/src/main/com/csse3200/game/areas/OceanGameAreaConfigs/OceanTileConfig.java
  source/core/src/main/com/csse3200/game/areas/OceanGameAreaConfigs/SoundsConfig.java
  source/core/src/main/com/csse3200/game/areas/OceanGameAreaConfigs/TexturesConfig.java
  source/core/src/main/com/csse3200/game/areas/WaterGameArea.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainChunk.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainComponent.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainFactory.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/entities/factories/ObstacleFactory.java
  source/core/src/test/com/csse3200/game/areas/terrain/TerrainChunkTest.java
Labels: Team 8

#454 FIX BUG: End of combat dialogue box does not show after win
  source/core/src/main/com/csse3200/game/components/combat/CombatActions.java
Labels: Team 9

#432 Inventory and item use accessible in Combat
  source/core/src/main/com/csse3200/game/components/combat/CombatActions.java
  source/core/src/main/com/csse3200/game/components/combat/CombatButtonDisplay.java
  source/core/src/main/com/csse3200/game/components/combat/CombatManager.java
  source/core/src/main/com/csse3200/game/components/combat/CombatStatsDisplay.java
  source/core/src/main/com/csse3200/game/components/combat/move/CombatMoveComponent.java
  source/core/src/main/com/csse3200/game/components/combat/move/ItemMove.java
  source/core/src/main/com/csse3200/game/components/inventory/CombatInventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/inventory/InventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/inventory/PlayerInventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/tasks/ItemProximityTask.java
  source/core/src/main/com/csse3200/game/components/tasks/TimedUseItemTask.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/inventory/items/AbstractItem.java
  source/core/src/main/com/csse3200/game/inventory/items/TimedUseItem.java
  source/core/src/main/com/csse3200/game/inventory/items/potions/AttackPotion.java
  source/core/src/main/com/csse3200/game/inventory/items/potions/DefensePotion.java
  source/core/src/main/com/csse3200/game/inventory/items/potions/SpeedPotion.java
  source/core/src/main/com/csse3200/game/screens/CombatScreen.java
  source/core/src/test/com/csse3200/game/inventory/items/TimedUseItemTest.java
Labels: Feature Ticket, Sprint 3, Team 3, Team 10

#427 4/NPC-Atlas-Update: Optimised NPC Atlases and Added Selection Highlight Feature
  source/core/assets/configs/ForestGameAreaConfigs/textures.json
  source/core/assets/configs/NPCs.json
  source/core/assets/images/Cow.atlas
  source/core/assets/images/Cow.png
  source/core/assets/images/Fish.atlas
  source/core/assets/images/Fish.png
  source/core/assets/images/cow.png
  source/core/assets/images/eagle.atlas
  source/core/assets/images/eagle.png
  source/core/assets/images/friendly_npcs/Cow.atlas
  source/core/assets/images/friendly_npcs/Fish.atlas
  source/core/assets/images/friendly_npcs/eagle.atlas
  source/core/assets/images/friendly_npcs/friendly-npcs.png
  source/core/assets/images/friendly_npcs/lion.atlas
  source/core/assets/images/friendly_npcs/magpie.atlas
  source/core/assets/images/friendly_npcs/snake.atlas
  source/core/assets/images/friendly_npcs/turtle.atlas
  source/core/assets/images/lion.atlas
  source/core/assets/images/lion.png
  source/core/assets/images/magpie.atlas
  source/core/assets/images/magpie.png
  source/core/assets/images/snake.atlas
  source/core/assets/images/snake.png
  source/core/assets/images/turtle.atlas
  source/core/assets/images/turtle.png
  source/core/src/main/com/csse3200/game/areas/CombatArea.java
  source/core/src/main/com/csse3200/game/components/tasks/PauseTask.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/services/DialogueBoxService.java
  source/core/src/test/com/csse3200/game/entities/DialogueBoxServiceTest.java
  source/core/src/test/com/csse3200/game/entities/factories/NPCFactoryTest.java
  source/desktop/src/com/csse3200/game/desktop/DesktopLauncher.java
Labels: Sprint 3

#437 [Team 10] Hovering Mouse over combat move provides additional info
  source/core/src/main/com/csse3200/game/components/combat/CombatButtonDisplay.java
Labels: Sprint 3, Team 10

#456 10/combat animations
  source/core/assets/images/flipped_fireball.png
  source/core/assets/images/shield.png
  source/core/assets/images/shield_flipped.png
  source/core/assets/images/single_fireball.png
  source/core/assets/images/zzz.png
  source/core/src/main/com/csse3200/game/areas/CombatArea.java
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/combat/CombatManager.java
  source/core/src/main/com/csse3200/game/components/quests/AchievementDisplay.java
  source/core/src/main/com/csse3200/game/entities/configs/BaseFriendlyEntityConfig.java
  source/core/src/main/com/csse3200/game/overlays/CombatAnimationDisplay.java
  source/core/src/main/com/csse3200/game/screens/CombatScreen.java
  source/core/src/test/com/csse3200/game/areas/CombatAreaTest.java
  source/core/src/test/com/csse3200/game/combat/CombatScreenTest.java
Labels: Sprint 3, Team 10

#471 [Team 10] Boss Special Move Status Effects with UI
  source/core/assets/images/statuses/bleeding_stat.png
  source/core/assets/images/statuses/confused_stat.png
  source/core/assets/images/statuses/poisoned_stat.png
  source/core/assets/images/statuses/shocked_stat.png
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/combat/CombatManager.java
  source/core/src/main/com/csse3200/game/components/combat/CombatStatsDisplay.java
  source/core/src/main/com/csse3200/game/components/combat/move/AttackMove.java
  source/core/src/main/com/csse3200/game/components/combat/move/SleepMove.java
  source/core/src/main/com/csse3200/game/components/combat/move/SpecialAirMove.java
  source/core/src/main/com/csse3200/game/components/combat/move/SpecialKangaMove.java
  source/core/src/main/com/csse3200/game/components/combat/move/SpecialWaterMove.java
  source/core/src/main/com/csse3200/game/screens/CombatScreen.java
  source/core/src/test/com/csse3200/game/components/combat/move/SpecialAirMoveTest.java
  source/core/src/test/com/csse3200/game/components/combat/move/SpecialKangaMoveTest.java
  source/core/src/test/com/csse3200/game/components/combat/move/SpecialWaterMoveTest.java
Labels: Sprint 3, Team 10

#469 10/Track enemy moves
  source/core/src/main/com/csse3200/game/components/combat/CombatManager.java
  source/core/src/main/com/csse3200/game/ui/terminal/Terminal.java
Labels: Sprint 3

#431 6 start settings
  assets/wiki/UML/gamearea/MiniMap.png
  assets/wiki/UML/login/LoginUML.png
  source/core/assets/chatbot.png
  source/core/assets/images/BirdMain.png
  source/core/assets/images/SplashScreen/chatbot2.png
  source/core/assets/images/Story/CrocStory3.png
  source/core/assets/images/Story/CrocStory4.PNG
  source/core/assets/images/Story/CrocStory5.png
  source/core/assets/images/Story/CrocStory6.png
  source/core/assets/images/Story/CrocStory7.png
  source/core/assets/images/Story/DogStory2.png
  source/core/assets/images/Story/DogStory3.png
  source/core/assets/images/chatbot1.png
  source/core/assets/images/minigames/Background.png
  source/core/assets/images/minimap/greenDotPoint.png
  source/core/assets/images/minimap/redDotPoint.png
  source/core/assets/images/owl.png
  source/core/assets/images/owl3.png
  source/core/assets/sounds/owlhoot1.mp3
  source/core/assets/spriteSheets/BirdMain.atlas
  source/core/assets/spriteSheets/BirdMain.png
  source/core/assets/spriteSheets/DogMain.atlas
  source/core/assets/spriteSheets/DogMain.png
  source/core/src/main/com/csse3200/game/areas/MiniMap.puml
  source/core/src/main/com/csse3200/game/areas/MiniMapDisplay.java
  source/core/src/main/com/csse3200/game/components/loading/LoadingDisplay.java
  source/core/src/main/com/csse3200/game/components/loading/MoonActor.java
  source/core/src/main/com/csse3200/game/components/login/Login.puml
  source/core/src/main/com/csse3200/game/components/login/LoginRegisterDisplay.java
  source/core/src/main/com/csse3200/game/components/login/PlayFab.java
  source/core/src/main/com/csse3200/game/components/maingame/MainGameExitDisplay.java
  source/core/src/main/com/csse3200/game/components/maingame/TimeDisplay.java
  source/core/src/main/com/csse3200/game/components/mainmenu/Bird.java
  source/core/src/main/com/csse3200/game/components/mainmenu/BirdAnimation.java
  source/core/src/main/com/csse3200/game/components/mainmenu/ChatbotService.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuActions.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/mainmenu/Slides.java
  source/core/src/main/com/csse3200/game/minigames/MinigameRenderer.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/screens/MainMenuScreen.java
  source/core/src/main/com/csse3200/game/screens/SnakeScreen.java
  source/core/src/main/com/csse3200/game/screens/StoryScreen.java
  source/core/src/test/com/csse3200/game/components/chatbot/ChatbotServiceTest.java
  source/core/src/test/com/csse3200/game/components/loading/LoadingDisplayTest.java
  source/core/src/test/com/csse3200/game/components/login/PlayFabTest.java
  source/core/src/test/com/csse3200/game/components/mainmenu/MainMenuDisplayTest.java
Labels: Sprint 3, Team 6

#478 created roulette feature for air land and water
  source/core/src/main/com/csse3200/game/areas/CombatArea.java
  source/core/src/main/com/csse3200/game/components/animal/AirAnimalSelectionDisplay.java
  source/core/src/main/com/csse3200/game/components/animal/AnimalRouletteActions.java
  source/core/src/main/com/csse3200/game/components/animal/AnimalRouletteDisplay.java
  source/core/src/main/com/csse3200/game/components/animal/AnimalSelectionActions.java
  source/core/src/main/com/csse3200/game/components/animal/AnimalSelectionDisplay.java
  source/core/src/main/com/csse3200/game/components/animal/LandAnimalSelectionDisplay.java
  source/core/src/main/com/csse3200/game/components/animal/WaterAnimalSelectionDisplay.java
  source/core/src/main/com/csse3200/game/screens/AirAnimalSelectionScreen.java
  source/core/src/main/com/csse3200/game/screens/AnimalRouletteScreen.java
  source/core/src/main/com/csse3200/game/screens/AnimalSelectionScreen.java
  source/core/src/main/com/csse3200/game/screens/LandAnimalSelectionScreen.java
  source/core/src/main/com/csse3200/game/screens/WaterAnimalSelectionScreen.java
  source/core/src/main/com/csse3200/game/ui/PopUpDialogBox/PopupDialogBox.java
  source/core/src/test/com/csse3200/game/components/animal/AnimalSelectionActionsTest.java
Labels: Sprint 3, Team 1

#479 6 start settings
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/MiniMapDisplay.java
  source/core/src/test/com/csse3200/game/areas/MiniMapDisplayTest.java
  source/core/src/test/com/csse3200/game/components/login/PlayFabTest.java
Labels: Sprint 3, Team 6

#452 Friendly NPC & Quests Integration
  defaultsaves/minigame.json
  source/core/assets/configs/NPCs.json
  source/core/assets/defaultsaves/quests.json
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/quests/AbstractQuest.java
  source/core/src/main/com/csse3200/game/components/quests/AchievementManager.java
  source/core/src/main/com/csse3200/game/components/quests/DialogueKey.java
  source/core/src/main/com/csse3200/game/components/quests/QuestBasic.java
  source/core/src/main/com/csse3200/game/components/quests/QuestManager.java
  source/core/src/main/com/csse3200/game/components/tasks/ItemProximityTask.java
  source/core/src/main/com/csse3200/game/components/tasks/PauseTask.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/gamestate/GameState.java
  source/core/src/main/com/csse3200/game/gamestate/data/QuestSave.java
  source/core/src/main/com/csse3200/game/inventory/Inventory.java
  source/core/src/main/com/csse3200/game/overlays/QuestDisplay.java
  source/core/src/main/com/csse3200/game/ui/dialoguebox/DialogueBox.java
  source/core/src/test/com/csse3200/game/components/quests/DialogueKeyTest.java
  source/core/src/test/com/csse3200/game/components/quests/InventoryTest.java
  source/core/src/test/com/csse3200/game/components/quests/QuestBasicTest.java
  source/core/src/test/com/csse3200/game/components/quests/QuestManagerTest.java
  source/core/src/test/com/csse3200/game/components/stats/StatTest.java
  source/core/src/test/com/csse3200/game/components/tasks/PauseTaskTest.java
  source/core/src/test/com/csse3200/game/entities/factories/NPCFactoryTest.java
  source/core/src/test/com/csse3200/game/gamestate/SaveHandlerTest.java
Labels: Sprint 3, Team 4, Team 5

#422 Simple dialogue priority implementation
  source/core/src/main/com/csse3200/game/components/combat/CombatButtonDisplay.java
  source/core/src/main/com/csse3200/game/components/combat/CombatManager.java
  source/core/src/main/com/csse3200/game/components/inventory/CombatInventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/inventory/PlayerInventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/tasks/ItemProximityTask.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/services/DialogueBoxService.java
  source/core/src/test/com/csse3200/game/entities/DialogueBoxServiceTest.java
  source/core/src/test/com/csse3200/game/entities/factories/NPCFactoryTest.java
Labels: Sprint 3, Team 4

#484 [Team 1] Enhanced Animal Selection + Bug Fix with Dog Sound
  source/core/assets/images/animal/Dog.atlas
  source/core/assets/images/animal/Dog.png
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/animal/AnimalRouletteDisplay.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/player/PlayerAnimationController.java
  source/core/src/main/com/csse3200/game/screens/WaterAnimalSelectionScreen.java
  source/core/src/test/com/csse3200/game/components/CombatStatsComponentTest.java
  source/core/src/test/com/csse3200/game/components/animal/AnimalRouletteDisplayTest.java
  source/core/src/test/com/csse3200/game/components/loading/LoadingDisplayTest.java
  source/core/src/test/com/csse3200/game/components/stats/StatsDisplayTest.java
Labels: Feature Ticket, Sprint 3, Team 1

#488 [Team 9] - Update the triggers/listeners for spawning each bosses
  source/core/assets/defaultsaves/quests.json
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/combat/CombatActions.java
  source/core/src/main/com/csse3200/game/components/combat/CombatManager.java
  source/core/src/main/com/csse3200/game/components/quests/QuestManager.java
Labels: Sprint 3, Team 9

#483 5-Quests/Achievements
  source/core/assets/configs/achievements.json
  source/core/assets/defaultsaves/achievement/achievements.json
  source/core/assets/defaultsaves/quests.json
  source/core/assets/test/achievements.json
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuActions.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/quests/Achievement.java
  source/core/src/main/com/csse3200/game/components/quests/AchievementDisplay.java
  source/core/src/main/com/csse3200/game/components/quests/AchievementManager.java
  source/core/src/main/com/csse3200/game/components/quests/AchievementPopup.java
  source/core/src/main/com/csse3200/game/components/quests/Quest.java
  source/core/src/main/com/csse3200/game/components/quests/QuestBasic.java
  source/core/src/main/com/csse3200/game/components/quests/QuestManager.java
  source/core/src/main/com/csse3200/game/components/tasks/PauseTask.java
  source/core/src/main/com/csse3200/game/gamestate/Achievements.java
  source/core/src/main/com/csse3200/game/gamestate/data/AchievementSave.java
  source/core/src/main/com/csse3200/game/gamestate/data/QuestSave.java
  source/core/src/main/com/csse3200/game/gamestate/data/StatSave.java
  source/core/src/main/com/csse3200/game/overlays/QuestDisplay.java
  source/core/src/test/com/csse3200/game/components/quests/AchievementManagerTest.java
  source/core/src/test/com/csse3200/game/components/quests/InventoryTest.java
  source/core/src/test/com/csse3200/game/components/quests/QuestManagerTest.java
  source/core/src/test/com/csse3200/game/components/quests/QuestTest.java
  source/core/src/test/com/csse3200/game/components/stats/StatTest.java
  source/core/src/test/com/csse3200/game/gamestate/SaveHandlerTest.java
  source/core/src/test/com/csse3200/game/inventory/InventoryTest.java
Labels: Sprint 3, Team 5

#482 [Team 2 & Team 10] Enemy Animations in the Combat Screen
  source/core/assets/images/bear.atlas
  source/core/assets/images/bee.atlas
  source/core/assets/images/bigsawfish.atlas
  source/core/assets/images/eel.atlas
  source/core/assets/images/enemy-chicken.atlas
  source/core/assets/images/enemy-frog.atlas
  source/core/assets/images/enemy-monkey.atlas
  source/core/assets/images/macaw.atlas
  source/core/assets/images/pigeon.atlas
  source/core/src/main/com/csse3200/game/areas/CombatArea.java
  source/core/src/main/com/csse3200/game/components/combat/CombatAnimationController.java
  source/core/src/main/com/csse3200/game/components/combat/CombatButtonDisplay.java
  source/core/src/main/com/csse3200/game/components/combat/CombatManager.java
  source/core/src/main/com/csse3200/game/entities/factories/CombatAnimalFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/EnemyFactory.java
  source/core/src/main/com/csse3200/game/screens/CombatScreen.java
Labels: Sprint 3, Team 2, Team 10

#498 [Team 9 & 10] Add Combat Animations for Bosses
  source/core/assets/images/air_boss.atlas
  source/core/assets/images/final_boss_kangaroo.atlas
  source/core/assets/images/joey.atlas
  source/core/assets/images/water_boss.atlas
  source/core/src/main/com/csse3200/game/areas/CombatArea.java
  source/core/src/main/com/csse3200/game/entities/factories/CombatAnimalFactory.java
Labels: Sprint 3, Team 9, Team 10

#435 4/entity conversion
  source/core/assets/configs/ForestGameAreaConfigs/sounds.json
  source/core/assets/configs/ForestGameAreaConfigs/textures.json
  source/core/assets/configs/NPCs.json
  source/core/assets/configs/enemyNPCs.json
  source/core/assets/images/chicken.atlas
  source/core/assets/images/enemy-bear.atlas
  source/core/assets/images/enemy-bear.png
  source/core/assets/images/frog.atlas
  source/core/assets/images/monkey.atlas
  source/core/assets/sounds/chicken.wav
  source/core/assets/sounds/frog.wav
  source/core/assets/sounds/monkey.wav
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/components/combat/CombatActions.java
  source/core/src/main/com/csse3200/game/entities/EntityConverter.java
  source/core/src/main/com/csse3200/game/entities/configs/NPCConfigs.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/test/com/csse3200/game/areas/ForestGameAreaTest.java
  source/core/src/test/com/csse3200/game/entities/EntityConverterTest.java
  source/core/src/test/com/csse3200/game/entities/factories/EnemyFactoryTest.java
Labels: Sprint 3, Team 4

#473 Fixing Items Not Actually Being Used in CombatInventoryDisplay
  source/core/src/main/com/csse3200/game/components/combat/CombatManager.java
  source/core/src/main/com/csse3200/game/components/inventory/CombatInventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/inventory/InventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/inventory/PlayerInventoryDisplay.java
  source/core/src/test/com/csse3200/game/components/inventory/CombatInventoryDisplayTest.java
Labels: bug, Sprint 3, Team 10

#495 New Achievements and detail
  source/core/assets/defaultsaves/achievement/achievements.json
  source/core/assets/images/logbook/icons/update-3/airboss.png
  source/core/assets/images/logbook/icons/update-3/bear.png
  source/core/assets/images/logbook/icons/update-3/bee.png
  source/core/assets/images/logbook/icons/update-3/bigsawfish.png
  source/core/assets/images/logbook/icons/update-3/eel.png
  source/core/assets/images/logbook/icons/update-3/fish-bronze.png
  source/core/assets/images/logbook/icons/update-3/fish-gold.png
  source/core/assets/images/logbook/icons/update-3/fish-silver.png
  source/core/assets/images/logbook/icons/update-3/joey.png
  source/core/assets/images/logbook/icons/update-3/lootbox.png
  source/core/assets/images/logbook/icons/update-3/macaw.png
  source/core/assets/images/logbook/icons/update-3/milk.png
  source/core/assets/images/logbook/icons/update-3/pigeon.png
  source/core/assets/images/logbook/icons/update-3/piranha.png
  source/core/assets/images/logbook/icons/update-3/sushi.png
  source/core/assets/images/logbook/icons/update-3/waterboss.png
  source/core/src/main/com/csse3200/game/components/quests/AchievementDisplay.java
Labels: Sprint 3, Team 5

#489 Creating Gates between each new area
  source/core/assets/configs/FogGameAreaConfigs/fogTiles.json
  source/core/assets/configs/FogGameAreaConfigs/textures.json
  source/core/assets/configs/ForestGameAreaConfigs/entitySpawn.json
  source/core/assets/configs/ForestGameAreaConfigs/textures.json
  source/core/assets/configs/OceanGameAreaConfigs/textures.json
  source/core/assets/images/cloud.png
  source/core/assets/images/fog-gate.jpg
  source/core/assets/images/fog-gate.png
  source/core/assets/images/old_tree.png
  source/core/assets/images/seaweed.png
  source/core/assets/images/starfish.png
  source/core/assets/images/tree.png
  source/core/src/main/com/csse3200/game/areas/FogBoarderArea.java
  source/core/src/main/com/csse3200/game/areas/FogGameAreaConfigs/FogGameAreaConfig.java
  source/core/src/main/com/csse3200/game/areas/FogGameAreaConfigs/FogMapTiles.java
  source/core/src/main/com/csse3200/game/areas/FogGameAreaConfigs/FogTileConfig.java
  source/core/src/main/com/csse3200/game/areas/FogGameAreaConfigs/TexturesConfig.java
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/ForestGameAreaConfigs/EntitySpawnConfig.java
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/areas/MapHandler.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainChunk.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainComponent.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainFactory.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/entities/factories/ObstacleFactory.java
  source/core/src/test/com/csse3200/game/entities/factories/ObstacleFactoryTest.java
Labels: Sprint 3, Team 3, Team 8

#505 [Team 9] Add key press to test the spawn of bosses
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/combat/CombatActions.java
  source/core/src/main/com/csse3200/game/components/combat/CombatButtonDisplay.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
Labels: Sprint 3, Team 9

#493 [Team 2] Add new enemy Octopus and add hive task test
  source/core/assets/configs/ForestGameAreaConfigs/entitySpawn.json
  source/core/assets/configs/ForestGameAreaConfigs/textures.json
  source/core/assets/configs/OceanGameAreaConfigs/entitySpawn.json
  source/core/assets/configs/enemyNPCs.json
  source/core/assets/images/octopus.atlas
  source/core/assets/images/octopus.png
  source/core/assets/images/octopus_idle.png
  source/core/src/main/com/csse3200/game/ai/tasks/AITaskComponent.java
  source/core/src/main/com/csse3200/game/areas/CombatArea.java
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/ForestGameAreaConfigs/EntitySpawnConfig.java
  source/core/src/main/com/csse3200/game/components/npc/OctopusAnimationController.java
  source/core/src/main/com/csse3200/game/components/tasks/HiveTask.java
  source/core/src/main/com/csse3200/game/entities/Entity.java
  source/core/src/main/com/csse3200/game/entities/configs/NPCConfigs.java
  source/core/src/main/com/csse3200/game/entities/factories/EnemyFactory.java
  source/core/src/main/com/csse3200/game/screens/EnemyCutsceneScreen.java
  source/core/src/test/com/csse3200/game/components/tasks/HiveTaskTest.java
  source/core/src/test/com/csse3200/game/entities/factories/ProjectileFactoryTest.java
Labels: Sprint 3, Team 2

#509 [Team 8] Cleanup
  source/core/src/main/com/csse3200/game/areas/CombatArea.java
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/ForestGameAreaConfigs/ForestMapTiles.java
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/areas/MapHandler.java
  source/core/src/main/com/csse3200/game/areas/MiniMapDisplay.java
  source/core/src/main/com/csse3200/game/areas/OceanGameAreaConfigs/OceanMapTiles.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainChunk.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainComponent.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainFactory.java
  source/core/src/test/com/csse3200/game/areas/ForestGameAreaTest.java
  source/core/src/test/com/csse3200/game/areas/GameAreaTest.java
  source/core/src/test/com/csse3200/game/areas/MiniMapDisplayTest.java
  source/core/src/test/com/csse3200/game/components/login/PlayFabTest.java
  source/core/src/test/com/csse3200/game/components/mainmenu/MainMenuDisplayTest.java
  source/core/src/test/com/csse3200/game/components/stats/StatsDisplayTest.java
Labels: Sprint 3, Team 8

#510 Bug fix - Stopped game from crashing when an entity is being converted
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
Labels: bug, Sprint 3, Team 4

#534 [Team 4's Code Clean Up]
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/tasks/PauseTask.java
  source/core/src/main/com/csse3200/game/entities/configs/BaseEnemyEntityConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/BaseEntityConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/BaseFriendlyEntityConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/ui/dialoguebox/KeyboardDialogueBoxInputComponent.java
  source/core/src/test/com/csse3200/game/components/tasks/PauseTaskTest.java
  source/core/src/test/com/csse3200/game/entities/factories/NPCFactoryTest.java
Labels: Task Ticket, Sprint 4

#540 Code Clean Up [Team 3]
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/components/combat/CombatManager.java
  source/core/src/main/com/csse3200/game/components/inventory/InventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/inventory/PlayerInventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/lootboxview/LootBoxOverlayComponent.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/inventory/Inventory.java
  source/core/src/main/com/csse3200/game/inventory/items/AbstractItem.java
  source/core/src/main/com/csse3200/game/inventory/items/ItemUsageContext.java
  source/core/src/main/com/csse3200/game/inventory/items/TimedUseItem.java
  source/core/src/main/com/csse3200/game/inventory/items/food/AbstractFood.java
  source/core/src/main/com/csse3200/game/inventory/items/food/Foods.java
  source/core/src/main/com/csse3200/game/inventory/items/lootbox/UniversalLootBox.java
  source/core/src/main/com/csse3200/game/inventory/items/lootbox/configs/BaseLootTable.java
  source/core/src/main/com/csse3200/game/inventory/items/lootbox/configs/LootItemConfig.java
  source/core/src/test/com/csse3200/game/inventory/items/FoodItemTest.java
Labels: Sprint 4, Team 3

#551 Further Sonar Cloud Clean Up
  source/core/assets/configs/ForestGameAreaConfigs/entitySpawn.json
  source/core/assets/configs/ForestGameAreaConfigs/sounds.json
  source/core/assets/configs/ForestGameAreaConfigs/textures.json
  source/core/src/main/com/csse3200/game/GdxGameManager.java
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/ForestGameAreaConfigs/EntitySpawnConfig.java
  source/core/src/main/com/csse3200/game/areas/ForestGameAreaConfigs/ForestGameAreaConfig.java
  source/core/src/main/com/csse3200/game/areas/ForestGameAreaConfigs/ForestSoundsConfig.java
  source/core/src/main/com/csse3200/game/areas/ForestGameAreaConfigs/ForestSpawnConfig.java
  source/core/src/main/com/csse3200/game/areas/ForestGameAreaConfigs/ForestTexturesConfig.java
  source/core/src/main/com/csse3200/game/areas/ForestGameAreaConfigs/SoundsConfig.java
  source/core/src/main/com/csse3200/game/areas/ForestGameAreaConfigs/TexturesConfig.java
  source/core/src/main/com/csse3200/game/areas/MiniMapDisplay.java
  source/core/src/main/com/csse3200/game/areas/OceanGameAreaConfigs/OceanGameAreaConfig.java
  source/core/src/main/com/csse3200/game/areas/combat/CombatArea.java
  source/core/src/main/com/csse3200/game/areas/combat/CombatAreaConfig.java
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/combat/CombatActions.java
  source/core/src/main/com/csse3200/game/components/combat/CombatButtonDisplay.java
  source/core/src/main/com/csse3200/game/components/combat/CombatManager.java
  source/core/src/main/com/csse3200/game/components/combat/move/CombatMove.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuActions.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/csse3200/game/inventory/items/potions/AttackPotion.java
  source/core/src/main/com/csse3200/game/inventory/items/potions/DefensePotion.java
  source/core/src/main/com/csse3200/game/inventory/items/potions/HealingPotion.java
  source/core/src/main/com/csse3200/game/inventory/items/potions/SpeedPotion.java
  source/core/src/main/com/csse3200/game/screens/CombatScreen.java
  source/core/src/test/com/csse3200/game/areas/CombatAreaTest.java
  source/core/src/test/com/csse3200/game/components/CombatStatsComponentTest.java
Labels: bug, Team 3

#552 More Code Clean Up
  source/core/assets/configs/ForestGameAreaConfigs/forestTiles.json
  source/core/src/main/com/csse3200/game/areas/ForestGameAreaConfigs/ForestMapTiles.java
  source/core/src/main/com/csse3200/game/areas/ForestGameAreaConfigs/ForestTileConfig.java
  source/core/src/main/com/csse3200/game/areas/MapHandler.java
  source/core/src/main/com/csse3200/game/areas/OceanGameAreaConfigs/OceanGameAreaConfig.java
  source/core/src/main/com/csse3200/game/areas/forest/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/forest/ForestSoundsConfig.java
  source/core/src/main/com/csse3200/game/areas/forest/ForestSpawnConfig.java
  source/core/src/main/com/csse3200/game/areas/forest/ForestTexturesConfig.java
  source/core/src/main/com/csse3200/game/areas/terrain/CombatTerrainFactory.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainChunk.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainComponent.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainFactory.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainLoader.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainResource.java
  source/core/src/main/com/csse3200/game/areas/terrain/tiles/ForestTileConfig.java
  source/core/src/main/com/csse3200/game/areas/terrain/tiles/Tile.java
  source/core/src/main/com/csse3200/game/components/animal/AnimalRouletteActions.java
  source/core/src/main/com/csse3200/game/components/animal/AnimalRouletteActions1.java
  source/core/src/main/com/csse3200/game/components/combat/move/SpecialAirMove.java
  source/core/src/main/com/csse3200/game/components/combat/move/SpecialKangaMove.java
  source/core/src/main/com/csse3200/game/components/combat/move/SpecialWaterMove.java
  source/core/src/main/com/csse3200/game/components/tasks/ChaseTask.java
  source/core/src/main/com/csse3200/game/components/tasks/LeviathanTask.java
  source/core/src/main/com/csse3200/game/components/tasks/StealTask.java
  source/core/src/main/com/csse3200/game/entities/factories/EnemyFactory.java
  source/core/src/main/com/csse3200/game/minigames/maze/Maze.java
  source/core/src/main/com/csse3200/game/minigames/maze/areas/MazeGameArea.java
  source/core/src/main/com/csse3200/game/minigames/maze/components/PlayerStunStatusEffect.java
  source/core/src/main/com/csse3200/game/minigames/maze/components/npc/EelVisualEffects.java
  source/core/src/main/com/csse3200/game/minigames/maze/components/tasks/MazePathFindingTask.java
  source/core/src/main/com/csse3200/game/screens/AirAnimalSelectionScreen1.java
  source/core/src/main/com/csse3200/game/screens/AnimalRouletteScreen.java
  source/core/src/main/com/csse3200/game/screens/AnimalRouletteScreen1.java
  source/core/src/main/com/csse3200/game/screens/LandAnimalSelectionScreen.java
  source/core/src/main/com/csse3200/game/screens/WaterAnimalSelectionScreen.java
  source/core/src/main/com/csse3200/game/screens/WaterAnimalSelectionScreen1.java
  source/core/src/main/com/csse3200/game/ui/UIComponent.java
  source/core/src/main/com/csse3200/game/ui/pop_up_dialog_box/PopUpHelper.java
  source/core/src/main/com/csse3200/game/ui/pop_up_dialog_box/PopupDialogBox.java
  source/core/src/main/com/csse3200/game/utils/math/GridPoint2Utils.java
  source/core/src/test/com/csse3200/game/areas/ForestGameAreaTest.java
  source/core/src/test/com/csse3200/game/areas/terrain/TerrainChunkTest.java
  source/core/src/test/com/csse3200/game/minigames/maze/MazeTest.java
  source/core/src/test/com/csse3200/game/ui/pop_up_dialog_box/PopUpHelperTest.java
  source/core/src/test/com/csse3200/game/ui/pop_up_dialog_box/PopupDialogBoxTest.java
Labels: bug, Sprint 4, Team 3

#560 Reducing Code Duplication
  source/core/src/main/com/csse3200/game/components/animal/AirAnimalSelectionDisplay.java
  source/core/src/main/com/csse3200/game/components/animal/AnimalRouletteDisplay1.java
  source/core/src/main/com/csse3200/game/components/animal/LandAnimalSelectionDisplay.java
  source/core/src/main/com/csse3200/game/components/animal/WaterAnimalSelectionDisplay.java
  source/core/src/main/com/csse3200/game/screens/AchievementsScreen.java
  source/core/src/main/com/csse3200/game/screens/AnimalRouletteScreen.java
  source/core/src/main/com/csse3200/game/screens/BirdieDashScreen.java
  source/core/src/main/com/csse3200/game/screens/BossCutsceneScreen.java
  source/core/src/main/com/csse3200/game/screens/CombatScreen.java
  source/core/src/main/com/csse3200/game/screens/EndGameStatsScreen.java
  source/core/src/main/com/csse3200/game/screens/EndMiniGameScreen.java
  source/core/src/main/com/csse3200/game/screens/EnemyCutsceneScreen.java
  source/core/src/main/com/csse3200/game/screens/GameOverLoseScreen.java
  source/core/src/main/com/csse3200/game/screens/LandAnimalSelectionScreen.java
  source/core/src/main/com/csse3200/game/screens/LoadingScreen.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/screens/MainMenuScreen.java
  source/core/src/main/com/csse3200/game/screens/MazeGameScreen.java
  source/core/src/main/com/csse3200/game/screens/MiniGameMenuScreen.java
  source/core/src/main/com/csse3200/game/screens/PausableScreen.java
  source/core/src/main/com/csse3200/game/screens/QuickTimeEventScreen.java
  source/core/src/main/com/csse3200/game/screens/ResizableScreen.java
  source/core/src/main/com/csse3200/game/screens/SnakeScreen.java
  source/core/src/main/com/csse3200/game/services/DialogueBoxService.java
Labels: bug, Sprint 4

#566 Fix Crash after Combat Bug
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainResource.java
Labels: bug

#570 Fix SonarCloud Warning for area package
  source/core/src/main/com/csse3200/game/areas/FogBoarderArea.java
  source/core/src/main/com/csse3200/game/areas/MapHandler.java
  source/core/src/main/com/csse3200/game/areas/terrain/CCell.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainChunk.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainComponent.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainResource.java
  source/core/src/main/com/csse3200/game/areas/terrain/tiles/Tile.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
Labels: bug, Sprint 4, Team 3, Team 8, Collaboration Ticket

#577 [Team 2] Resolving all Reliability issues
  source/core/src/main/com/csse3200/game/areas/MiniMapDisplay.java
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/combat/quicktimeevent/QuickTimeEventDisplay.java
  source/core/src/main/com/csse3200/game/components/gameover/GameOverLoseDisplay.java
  source/core/src/main/com/csse3200/game/components/inventory/PlayerInventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/mainmenu/HelpWindow.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/quests/AchievementDisplay.java
  source/core/src/main/com/csse3200/game/components/settingsmenu/SettingsMenu.java
  source/core/src/main/com/csse3200/game/components/stats/StatDisplay.java
  source/core/src/main/com/csse3200/game/components/story/StoryDisplay.java
  source/core/src/main/com/csse3200/game/minigames/maze/Maze.java
Labels: bug, Sprint 4, Team 2

#585 Collaborative Refactoring Out SonarCloud Smells
  source/core/src/main/com/csse3200/game/areas/MiniMapDisplay.java
  source/core/src/main/com/csse3200/game/areas/combat/CombatAreaConfig.java
  source/core/src/main/com/csse3200/game/areas/forest/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/animal/AirAnimalSelectionDisplay.java
  source/core/src/main/com/csse3200/game/components/animal/LandAnimalSelectionDisplay.java
  source/core/src/main/com/csse3200/game/components/animal/WaterAnimalSelectionDisplay.java
Labels: bug, Team 2, Team 3, Collaboration Ticket

#563 Adding zone spawn to the FNPCs
  source/core/assets/configs/NPCs.json
  source/core/src/main/com/csse3200/game/areas/forest/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/forest/ForestSpawnConfig.java
  source/core/src/test/com/csse3200/game/entities/factories/NPCFactoryTest.java
Labels: Task Ticket, Team 4

#569 3/546 introduce new items and spawn control
  source/core/assets/configs/OceanGameAreaConfigs/entitySpawn.json
  source/core/assets/configs/OceanGameAreaConfigs/entitySpawnLocked.json
  source/core/assets/images/foodtextures/airfoodtextures/cloud-cookie.png
  source/core/assets/images/foodtextures/airfoodtextures/cloudCupcake.png
  source/core/assets/images/foodtextures/airfoodtextures/cotton-cloud.png
  source/core/assets/images/foodtextures/oceanfoodtextures/fried-fish.png
  source/core/assets/images/foodtextures/oceanfoodtextures/shrimp.png
  source/core/assets/images/foodtextures/shrimp.png
  source/core/src/main/com/csse3200/game/areas/OceanGameAreaConfigs/OceanGameAreaConfig.java
  source/core/src/main/com/csse3200/game/areas/forest/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/forest/ForestSpawnConfig.java
  source/core/src/main/com/csse3200/game/areas/forest/ForestTexturesConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/ItemFactory.java
  source/core/src/main/com/csse3200/game/inventory/items/TimedUseItem.java
  source/core/src/main/com/csse3200/game/inventory/items/food/Foods.java
  source/core/src/main/com/csse3200/game/inventory/items/potions/SpeedPotion.java
Labels: bug, Task Ticket, Team 3

#574 530 stamina ‍to hunger
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/combat/CombatActions.java
  source/core/src/main/com/csse3200/game/components/combat/CombatButtonDisplay.java
  source/core/src/main/com/csse3200/game/components/combat/CombatExitDisplay.java
  source/core/src/main/com/csse3200/game/components/combat/CombatManager.java
  source/core/src/main/com/csse3200/game/components/combat/CombatStatsDisplay.java
  source/core/src/main/com/csse3200/game/components/combat/move/AttackMove.java
  source/core/src/main/com/csse3200/game/components/combat/move/CombatMove.java
  source/core/src/main/com/csse3200/game/components/combat/move/GuardMove.java
  source/core/src/main/com/csse3200/game/components/combat/move/ItemMove.java
  source/core/src/main/com/csse3200/game/components/combat/move/SleepMove.java
  source/core/src/main/com/csse3200/game/components/combat/move/SpecialAirMove.java
  source/core/src/main/com/csse3200/game/components/combat/move/SpecialKangaMove.java
  source/core/src/main/com/csse3200/game/components/combat/move/SpecialMove.java
  source/core/src/main/com/csse3200/game/components/combat/move/SpecialWaterMove.java
  source/core/src/main/com/csse3200/game/components/mainmenu/Slides.java
  source/core/src/main/com/csse3200/game/components/player/PlayerStatsDisplay.java
  source/core/src/main/com/csse3200/game/entities/configs/BaseEnemyEntityConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/BaseFriendlyEntityConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/BossFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/EnemyFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/test/com/csse3200/game/components/CombatStatsComponentTest.java
  source/core/src/test/com/csse3200/game/components/ProjectileAttackComponentTest.java
  source/core/src/test/com/csse3200/game/components/TouchAttackComponentTest.java
  source/core/src/test/com/csse3200/game/components/combat/move/AttackMoveTest.java
  source/core/src/test/com/csse3200/game/components/combat/move/CombatMoveTest.java
  source/core/src/test/com/csse3200/game/components/combat/move/GuardMoveTest.java
  source/core/src/test/com/csse3200/game/components/combat/move/SleepMoveTest.java
  source/core/src/test/com/csse3200/game/components/combat/move/SpecialAirMoveTest.java
  source/core/src/test/com/csse3200/game/components/combat/move/SpecialKangaMoveTest.java
  source/core/src/test/com/csse3200/game/components/combat/move/SpecialMoveTest.java
  source/core/src/test/com/csse3200/game/components/combat/move/SpecialWaterMoveTest.java
  source/core/src/test/com/csse3200/game/inventory/items/AbstractFoodTest.java
  source/core/src/test/com/csse3200/game/inventory/items/FoodItemTest.java
  source/core/src/test/com/csse3200/game/inventory/items/TimedUseItemTest.java
Labels: Sprint 4, Team 10

#596 [Team 9] Remove BossAnimationControllers Duplication
  source/core/src/main/com/csse3200/game/components/npc/AirBossAnimationController.java
  source/core/src/main/com/csse3200/game/components/npc/BossAnimationController.java
  source/core/src/main/com/csse3200/game/components/npc/KangaBossAnimationController.java
  source/core/src/main/com/csse3200/game/components/npc/WaterBossAnimationController.java
  source/core/src/main/com/csse3200/game/entities/factories/BossFactory.java
  source/core/src/test/com/csse3200/game/entities/factories/BossFactoryTest.java
Labels: Sprint 4, Team 9

#606 [Team 9] Update boss spawns location, and tension music to use AudioManager
  source/core/assets/configs/OceanGameAreaConfigs/sounds.json
  source/core/assets/sounds/heartbeat.mp3
  source/core/assets/sounds/tension-air-boss.mp3
  source/core/assets/sounds/tension-land-boss.mp3
  source/core/assets/sounds/tension-water-boss.mp3
  source/core/src/main/com/csse3200/game/areas/combat/CombatArea.java
  source/core/src/main/com/csse3200/game/areas/combat/CombatAreaConfig.java
  source/core/src/main/com/csse3200/game/areas/forest/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/forest/ForestSoundsConfig.java
  source/core/src/main/com/csse3200/game/components/tasks/ChaseTask.java
  source/core/src/main/com/csse3200/game/components/tasks/GriffinTask.java
  source/core/src/main/com/csse3200/game/components/tasks/LeviathanTask.java
  source/core/src/main/com/csse3200/game/entities/factories/BossFactory.java
  source/core/src/test/com/csse3200/game/entities/factories/BossFactoryTest.java
Labels: Sprint 4, Team 9

#621 Bug Fix to Incorrect Handling of Losing in Combat
  source/core/src/main/com/csse3200/game/components/combat/CombatActions.java
  source/core/src/main/com/csse3200/game/components/combat/CombatButtonDisplay.java
  source/core/src/main/com/csse3200/game/components/combat/CombatManager.java
  source/core/src/main/com/csse3200/game/components/combat/CombatStatsDisplay.java
  source/core/src/main/com/csse3200/game/components/inventory/PlayerInventoryDisplay.java
Labels: bug, Sprint 4, Team 10

#630 1/player shaivika
  source/core/assets/images/animal/Black and White Modern Forest Scenery At Night Desktop Wallpapaer.png
  source/core/assets/sounds/animal/birds-and-animals-before-sunrise-246785.mp3
  source/core/src/main/com/csse3200/game/components/animal/AnimalRouletteActions1.java
  source/core/src/main/com/csse3200/game/components/animal/AnimalRouletteDisplay1.java
  source/core/src/main/com/csse3200/game/screens/AnimalRouletteScreen1.java
  source/core/src/main/com/csse3200/game/screens/CutSceneScreen.java
  source/core/src/main/com/csse3200/game/ui/pop_up_dialog_box/PopupDialogBox.java
Labels: Sprint 4, Team 1

#633 improved roulette feature and fixed bug
  source/core/src/main/com/csse3200/game/components/animal/AnimalRouletteActions1.java
  source/core/src/main/com/csse3200/game/components/animal/AnimalRouletteDisplay1.java
  source/core/src/main/com/csse3200/game/ui/pop_up_dialog_box/PopUpHelper.java
  source/core/src/main/com/csse3200/game/ui/pop_up_dialog_box/PopupDialogBox.java
Labels: Sprint 4, Team 1

#627 [Team 10] Enemy Animations in the Combat Screen
  source/core/assets/images/bear.atlas
  source/core/assets/images/bee.atlas
  source/core/assets/images/bigsawfish.atlas
  source/core/assets/images/eel.atlas
  source/core/assets/images/enemy-bear.atlas
  source/core/assets/images/enemy-chicken.atlas
  source/core/assets/images/enemy-frog.png
  source/core/assets/images/enemy-monkey.atlas
  source/core/assets/images/joey.atlas
  source/core/assets/images/macaw.atlas
  source/core/assets/images/octopus.atlas
  source/core/src/main/com/csse3200/game/entities/factories/CombatAnimalFactory.java
Labels: Sprint 4, Team 10

#629 Minigame popup
  source/core/assets/flat-earth/skin/flat-earth-ui.json
  source/core/assets/images/minigames/BirdieDashPopUp.png
  source/core/assets/images/minigames/MazePopUp.png
  source/core/assets/images/minigames/SnakePopUp.png
  source/core/src/main/com/csse3200/game/minigames/birdiedash/controller/KeyboardBirdInputComponent.java
  source/core/src/main/com/csse3200/game/minigames/snake/rendering/SnakeGameRenderer.java
  source/core/src/main/com/csse3200/game/overlays/Overlay.java
  source/core/src/main/com/csse3200/game/overlays/PauseDisplay.java
  source/core/src/main/com/csse3200/game/overlays/SnakePopupOverlay.java
  source/core/src/main/com/csse3200/game/screens/BirdieDashScreen.java
  source/core/src/main/com/csse3200/game/screens/MazeGameScreen.java
  source/core/src/main/com/csse3200/game/screens/MiniGameMenuScreen.java
  source/core/src/main/com/csse3200/game/screens/MiniGameScreen.java
  source/core/src/main/com/csse3200/game/screens/PausableScreen.java
  source/core/src/main/com/csse3200/game/screens/SnakePopup.java
  source/core/src/main/com/csse3200/game/screens/SnakeScreen.java
  source/core/src/main/com/csse3200/game/ui/minigames/ScoreBoard.java
  source/core/src/test/com/csse3200/game/components/loading/LoadingDisplayTest.java
Labels: Sprint 4, Team 7

#625 [Team 10] Combat Sound Effects and UI Resizing
  source/core/assets/configs/enemyNPCs.json
  source/core/assets/images/air_background.png
  source/core/assets/images/frog.atlas
  source/core/assets/images/land_background.png
  source/core/assets/images/minimap/rock.png
  source/core/assets/images/rock.png
  source/core/assets/images/water_background.png
  source/core/assets/sounds/combat/attack blocked.wav
  source/core/assets/sounds/combat/attack hit.wav
  source/core/assets/sounds/combat/attack start.wav
  source/core/assets/sounds/combat/guard.wav
  source/core/assets/sounds/combat/sleep.wav
  source/core/assets/sounds/combat_track1.mp3
  source/core/src/main/com/csse3200/game/areas/combat/CombatArea.java
  source/core/src/main/com/csse3200/game/areas/combat/CombatAreaConfig.java
  source/core/src/main/com/csse3200/game/areas/forest/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/terrain/CombatTerrainFactory.java
  source/core/src/main/com/csse3200/game/components/combat/CombatManager.java
  source/core/src/main/com/csse3200/game/components/combat/CombatStatsDisplay.java
  source/core/src/main/com/csse3200/game/components/combat/quicktimeevent/CombatMoveAudio.java
  source/core/src/main/com/csse3200/game/entities/factories/CombatAnimalFactory.java
  source/core/src/main/com/csse3200/game/overlays/CombatAnimationDisplay.java
  source/core/src/test/com/csse3200/game/areas/CombatAreaTest.java
Labels: Sprint 4, Team 10

#636 Minigame Code Smells and extra testing
  source/core/src/main/com/csse3200/game/gamestate/data/MinigameHighscore.java
  source/core/src/main/com/csse3200/game/minigames/KeyboardMiniGameInputComponent.java
  source/core/src/main/com/csse3200/game/minigames/MinigameRenderer.java
  source/core/src/main/com/csse3200/game/minigames/birdiedash/BirdieDashGame.java
  source/core/src/main/com/csse3200/game/minigames/birdiedash/entities/Background.java
  source/core/src/main/com/csse3200/game/minigames/birdiedash/entities/Coin.java
  source/core/src/main/com/csse3200/game/minigames/birdiedash/entities/Pipe.java
  source/core/src/main/com/csse3200/game/minigames/birdiedash/entities/Spike.java
  source/core/src/main/com/csse3200/game/minigames/birdiedash/rendering/BackgroundRenderer.java
  source/core/src/main/com/csse3200/game/minigames/birdiedash/rendering/BirdRenderer.java
  source/core/src/main/com/csse3200/game/minigames/birdiedash/rendering/PipeRenderer.java
  source/core/src/main/com/csse3200/game/minigames/maze/areas/MazeGameArea.java
  source/core/src/main/com/csse3200/game/minigames/maze/components/MazeTouchAttackComponent.java
  source/core/src/main/com/csse3200/game/minigames/maze/components/NPCStunStatusEffect.java
  source/core/src/main/com/csse3200/game/minigames/maze/components/PlayerInkedStatusEffect.java
  source/core/src/main/com/csse3200/game/minigames/maze/components/StatusEffectComponent.java
  source/core/src/main/com/csse3200/game/minigames/maze/components/npc/TurtleCarryComponent.java
  source/core/src/main/com/csse3200/game/minigames/maze/entities/mazenpc/MazeEntity.java
  source/core/src/main/com/csse3200/game/minigames/maze/entities/mazenpc/Octopus.java
  source/core/src/main/com/csse3200/game/minigames/maze/entities/mazenpc/Turtle.java
  source/core/src/main/com/csse3200/game/minigames/maze/physics/MazePhysicsUtils.java
  source/core/src/main/com/csse3200/game/minigames/maze/rendering/AlphaTextureRenderComponent.java
  source/core/src/main/com/csse3200/game/minigames/snake/Snake.java
  source/core/src/main/com/csse3200/game/minigames/snake/rendering/GridRenderer.java
  source/core/src/main/com/csse3200/game/minigames/snake/rendering/SnakeGameRenderer.java
  source/core/src/main/com/csse3200/game/minigames/snake/rendering/SnakeRenderer.java
  source/core/src/main/com/csse3200/game/screens/BirdieDashScreen.java
  source/core/src/main/com/csse3200/game/screens/EndMiniGameScreen.java
  source/core/src/main/com/csse3200/game/screens/MazeGameScreen.java
  source/core/src/main/com/csse3200/game/screens/MiniGameMenuScreen.java
  source/core/src/main/com/csse3200/game/screens/SnakeScreen.java
  source/core/src/test/com/csse3200/game/minigames/GridCellTest.java
  source/core/src/test/com/csse3200/game/minigames/GridTest.java
  source/core/src/test/com/csse3200/game/minigames/birdiedash/entities/CoinTest.java
  source/core/src/test/com/csse3200/game/minigames/maze/components/tasks/MazePathFindingTaskTest.java
  source/core/src/test/com/csse3200/game/minigames/snake/AppleTest.java
  source/core/src/test/com/csse3200/game/minigames/snake/EventsTest.java
  source/core/src/test/com/csse3200/game/minigames/snake/SnakeGridTest.java
  source/core/src/test/com/csse3200/game/minigames/snake/SnakeTest.java
  source/core/src/test/com/csse3200/game/rendering/Minigames/Snake/SnakeRendererTest.java
Labels: Sprint 4, Team 7

#641 Added small test cases for item spawning
  source/core/src/main/com/csse3200/game/areas/forest/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/forest/ForestSpawnConfig.java
  source/core/src/main/com/csse3200/game/components/inventory/InventoryDisplay.java
  source/core/src/test/com/csse3200/game/entities/factories/ItemFactoryTest.java
Labels: Sprint 4, Team 3

#642 [Team 2 & 9] Pre-combat cutscene and general bosses tweak
  source/core/assets/configs/NPCs.json
  source/core/assets/configs/enemyNPCs.json
  source/core/assets/sounds/combat-air-boss.mp3
  source/core/assets/sounds/combat-land-boss.mp3
  source/core/assets/sounds/combat-water-boss.mp3
  source/core/assets/sounds/precombat.mp3
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/areas/combat/CombatArea.java
  source/core/src/main/com/csse3200/game/areas/combat/CombatAreaConfig.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/entities/factories/BossFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/CombatAnimalFactory.java
  source/core/src/main/com/csse3200/game/screens/BossCutsceneScreen.java
  source/core/src/main/com/csse3200/game/screens/EnemyCutsceneScreen.java
  source/core/src/main/com/csse3200/game/screens/PreCombatCutsceneScreen.java
  source/core/src/test/com/csse3200/game/areas/CombatAreaTest.java
  source/core/src/test/com/csse3200/game/entities/factories/NPCFactoryTest.java
  source/core/src/test/com/csse3200/game/entities/factories/ProjectileFactoryTest.java
Labels: enhancement, Sprint 4, Team 2, Team 9, Collaboration Ticket

#634 Quest clean up & display fixes
  source/core/assets/configs/NPCs.json
  source/core/assets/defaultsaves/quests.json
  source/core/assets/images/PauseOverlay/Button2.png
  source/core/assets/images/PauseOverlay/TitleBG.png
  source/core/src/main/com/csse3200/game/components/quests/Quest.java
  source/core/src/main/com/csse3200/game/components/quests/QuestManager.java
  source/core/src/main/com/csse3200/game/minigames/birdiedash/BirdieDashGame.java
  source/core/src/main/com/csse3200/game/minigames/maze/areas/MazeGameArea.java
  source/core/src/main/com/csse3200/game/minigames/snake/AssetPaths.java
  source/core/src/main/com/csse3200/game/overlays/PauseDisplay.java
  source/core/src/main/com/csse3200/game/overlays/PlayerStatsDisplay2.java
  source/core/src/main/com/csse3200/game/overlays/QuestDisplay.java
  source/core/src/main/com/csse3200/game/screens/CombatScreen.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/ui/CustomButton.java
  source/core/src/main/com/csse3200/game/ui/dialoguebox/DialogueBox.java
  source/core/src/test/com/csse3200/game/components/quests/QuestManagerTest.java
  source/core/src/test/com/csse3200/game/components/tasks/PauseTaskTest.java
  source/core/src/test/com/csse3200/game/entities/factories/NPCFactoryTest.java
Labels: Sprint 4, Team 5

#648 [Team 10] Combat Stats Change UI Enhancement
  source/core/src/main/com/csse3200/game/components/combat/CombatManager.java
  source/core/src/main/com/csse3200/game/components/combat/CombatStatsChangePopup.java
  source/core/src/main/com/csse3200/game/components/combat/CombatStatsDisplay.java
  source/core/src/main/com/csse3200/game/components/combat/move/AttackMove.java
  source/core/src/main/com/csse3200/game/components/combat/move/CombatMove.java
  source/core/src/main/com/csse3200/game/components/combat/move/CombatMoveComponent.java
  source/core/src/main/com/csse3200/game/components/combat/move/GuardMove.java
  source/core/src/main/com/csse3200/game/components/combat/move/ItemMove.java
  source/core/src/main/com/csse3200/game/components/combat/move/SleepMove.java
  source/core/src/main/com/csse3200/game/components/combat/move/SpecialMove.java
  source/core/src/test/com/csse3200/game/components/combat/move/CombatMoveTest.java
Labels: Sprint 4, Team 10

#646 [Team 10] Remove Combat Screen Exit Buttons
  source/core/src/main/com/csse3200/game/components/combat/CombatExitDisplay.java
  source/core/src/main/com/csse3200/game/components/combat/CombatStatsDisplay.java
  source/core/src/main/com/csse3200/game/screens/CombatScreen.java
Labels: Sprint 4, Team 10

#654 fixed inventory
  source/core/src/main/com/csse3200/game/components/inventory/InventoryDisplay.java
Labels: bug, Sprint 4, Team 3

#632 Quest saves refactor
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/components/combat/CombatManager.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuActions.java
  source/core/src/main/com/csse3200/game/components/quests/AchievementDisplay.java
  source/core/src/main/com/csse3200/game/components/quests/AchievementPopup.java
  source/core/src/main/com/csse3200/game/components/quests/Quest.java
  source/core/src/main/com/csse3200/game/components/quests/QuestHidden.java
  source/core/src/main/com/csse3200/game/components/quests/QuestManager.java
  source/core/src/main/com/csse3200/game/gamestate/Achievements.java
  source/core/src/main/com/csse3200/game/gamestate/GameState.java
  source/core/src/main/com/csse3200/game/gamestate/SaveHandler.java
  source/core/src/main/com/csse3200/game/gamestate/data/QuestSave.java
  source/core/src/main/com/csse3200/game/gamestate/data/StatSave.java
  source/core/src/main/com/csse3200/game/overlays/PauseDisplay.java
  source/core/src/main/com/csse3200/game/overlays/QuestDisplay.java
  source/core/src/main/com/csse3200/game/screens/BirdieDashScreen.java
  source/core/src/main/com/csse3200/game/screens/MazeGameScreen.java
  source/core/src/main/com/csse3200/game/screens/SnakeScreen.java
  source/core/src/test/com/csse3200/game/components/quests/AchievementManagerTest.java
  source/core/src/test/com/csse3200/game/components/quests/InventoryTest.java
  source/core/src/test/com/csse3200/game/components/quests/QuestHiddenTest.java
  source/core/src/test/com/csse3200/game/components/quests/QuestManagerTest.java
  source/core/src/test/com/csse3200/game/components/quests/QuestTest.java
  source/core/src/test/com/csse3200/game/components/stats/StatTest.java
  source/core/src/test/com/csse3200/game/components/tasks/PauseTaskTest.java
  source/core/src/test/com/csse3200/game/gamestate/SaveHandlerTest.java
  source/core/src/test/com/csse3200/game/inventory/InventoryTest.java
Labels: Sprint 4, Team 5

#657 [Team 10] Enemy Move Selector and Water Kingdom Combat Background
  source/core/src/main/com/csse3200/game/areas/combat/CombatArea.java
  source/core/src/main/com/csse3200/game/areas/terrain/CombatTerrainFactory.java
  source/core/src/main/com/csse3200/game/components/combat/CombatManager.java
  source/core/src/main/com/csse3200/game/components/combat/move/CombatMoveComponent.java
  source/core/src/main/com/csse3200/game/overlays/CombatAnimationDisplay.java
Labels: Sprint 4, Team 10

#623 Improved visuals for both QuestPopup and AchievementPopup
  source/core/assets/images/logbook-popup.png
  source/core/assets/images/quest-complete.png
  source/core/src/main/com/csse3200/game/components/quests/AchievementManager.java
  source/core/src/main/com/csse3200/game/components/quests/AchievementPopup.java
  source/core/src/main/com/csse3200/game/components/quests/QuestManager.java
  source/core/src/main/com/csse3200/game/components/quests/QuestPopup.java
  source/core/src/test/com/csse3200/game/components/quests/AchievementManagerTest.java
Labels: Sprint 4, Team 5

#607 Change of NPC dialogues to fit the terrain specific bosses
  source/core/assets/configs/NPCs.json
  source/core/src/test/com/csse3200/game/entities/factories/NPCFactoryTest.java
Labels: Sprint 4, Team 4

#618 Update Testing For Team 4
  source/core/src/main/com/csse3200/game/entities/configs/BaseFriendlyEntityConfig.java
  source/core/src/main/com/csse3200/game/minigames/maze/Maze.java
  source/core/src/test/com/csse3200/game/entities/DialogueBoxServiceTest.java
  source/core/src/test/com/csse3200/game/entities/configs/BaseFriendlyEntityConfigTest.java
  source/core/src/test/com/csse3200/game/entities/factories/NPCFactoryTest.java
  source/core/src/test/com/csse3200/game/minigames/maze/components/MazeTouchAttackComponentTest.java
Labels: Sprint 4, Team 4

#670 9 endgame stats
  source/core/assets/defaultsaves/stats.json
  source/core/assets/images/logbook/stats/lb-stats-air-tab.png
  source/core/assets/images/logbook/stats/lb-stats-combat-tab.png
  source/core/assets/images/logbook/stats/lb-stats-food-tab.png
  source/core/assets/images/logbook/stats/lb-stats-land-tab.png
  source/core/assets/images/logbook/stats/lb-stats-minigame-tab.png
  source/core/assets/images/logbook/stats/lb-stats-potion-tab.png
  source/core/assets/images/logbook/stats/lb-stats-water-tab.png
  source/core/src/main/com/csse3200/game/areas/forest/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/stats/Stat.java
  source/core/src/main/com/csse3200/game/components/stats/StatDisplay.java
  source/core/src/main/com/csse3200/game/components/stats/StatManager.java
  source/core/src/main/com/csse3200/game/components/stats/StatSaveManager.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/screens/EndMiniGameScreen.java
Labels: Sprint 4, Team 9

#667 Updated Score Thresholds
  source/core/src/main/com/csse3200/game/minigames/MiniGameConstants.java
Labels: Sprint 4, Team 7

#673 fixing javadoc so it doesn't fail
  source/core/src/main/com/csse3200/game/entities/configs/BaseFriendlyEntityConfig.java
Labels: bug, Sprint 4

#669 cleaned up quest/save functionality and added saves for player information
  source/core/assets/configs/defaultsaves/minigame.json
  source/core/assets/defaultsaves/player.json
  source/core/src/main/com/csse3200/game/areas/combat/CombatArea.java
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/animal/AnimalRouletteActions1.java
  source/core/src/main/com/csse3200/game/components/quests/QuestManager.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/gamestate/data/PlayerSave.java
  source/core/src/main/com/csse3200/game/gamestate/data/WorldState.java
Labels: Sprint 4, Team 1, Team 5, Collaboration Ticket

#672 Fixed comments and naming for StatDisply and Manager classes. Fixed p…
  source/core/assets/defaultsaves/stats.json
  source/core/src/main/com/csse3200/game/areas/forest/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/stats/Stat.java
  source/core/src/main/com/csse3200/game/components/stats/StatDisplay.java
  source/core/src/main/com/csse3200/game/components/stats/StatManager.java
Labels: Sprint 4, Team 9

#671 [Team 1 & 2] game balancing, XP adjustment and level up
  source/core/assets/configs/enemyNPCs.json
  source/core/src/main/com/csse3200/game/areas/forest/ForestSpawnConfig.java
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerStatsDisplay.java
  source/core/src/main/com/csse3200/game/entities/factories/EnemyFactory.java
  source/core/src/test/com/csse3200/game/components/CombatStatsComponentTest.java
  source/core/src/test/com/csse3200/game/entities/factories/BossFactoryTest.java
  source/core/src/test/com/csse3200/game/entities/factories/EnemyFactoryTest.java
Labels: Sprint 4, Team 1, Team 2, Collaboration Ticket

#675 [Team 2] fixing the hive disposing of bees multiple times
  source/core/src/main/com/csse3200/game/areas/forest/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/tasks/HiveTask.java
  source/core/src/main/com/csse3200/game/entities/Entity.java
  source/core/src/main/com/csse3200/game/entities/factories/ProjectileFactory.java
  source/core/src/test/com/csse3200/game/entities/factories/ProjectileFactoryTest.java
Labels: bug, Sprint 4, Team 2

#517 8 maptab
  source/core/assets/map/Lion_Icon.png
  source/core/assets/map/MAP.png
  source/core/assets/map/PlayerLocation.png
  source/core/assets/map/landmark_icon.png
  source/core/assets/map/north_symbol.png
  source/core/assets/map/x_button.png
  source/core/src/main/com/csse3200/game/areas/forest/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/CameraZoomComponent.java
  source/core/src/main/com/csse3200/game/components/gamearea/MapTabComponent.java
  source/core/src/main/com/csse3200/game/physics/PhysicsLayer.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
Labels: Sprint 4, Team 8

#676 [Team 9] Add Unit Tests and Defeating boss unlock next area
  hs_err_pid48000.log
  source/core/src/main/com/csse3200/game/components/combat/CombatActions.java
  source/core/src/main/com/csse3200/game/entities/factories/EnemyFactory.java
  source/core/src/test/com/csse3200/game/components/tasks/GriffinTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/KangaJoeyTaskTest.java
  source/core/src/test/com/csse3200/game/entities/factories/BossFactoryTest.java
  source/core/src/test/com/csse3200/game/entities/factories/EnemyFactoryTest.java
Labels: Sprint 4, Team 9

#679 [Team 9] Add lines to unlock the next area after defeat boss.
  source/core/src/main/com/csse3200/game/components/combat/CombatActions.java
Labels: Sprint 4, Team 9
